FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY cupnavi_core ./cupnavi_core
COPY cupnavi_api ./cupnavi_api
COPY VERSION.txt ./VERSION.txt

EXPOSE 8001
CMD ["uvicorn","cupnavi_api.main:app","--host","0.0.0.0","--port","8001","--proxy-headers"]
