"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { CLIENT_API_BASE } from "../lib/client-api";

type Member={id:number;email:string;display_name?:string|null;role:"owner"|"admin";created_at?:string|null};
type Activity={id:number;actor_email:string;summary:string;created_at:string};
type AccessPayload={members:Member[];current_role:string;can_manage:boolean};
type MemberResult={member:Member;temporary_password?:string|null;email_status?:"sent"|"not_configured"|"failed";email_error?:string|null};

async function req<T>(path:string,token:string,options:RequestInit={}):Promise<T>{
 const headers=new Headers(options.headers||{});headers.set("Authorization",`Bearer ${token}`);if(options.body)headers.set("Content-Type","application/json");
 const response=await fetch(`${CLIENT_API_BASE}${path}`,{...options,headers,cache:"no-store"});const payload=await response.json().catch(()=>null);
 if(!response.ok)throw new Error(payload?.detail||`API-fel ${response.status}`);return payload as T;
}

export default function AccessAdmin({token,cupId,accountId,isPlatformOwner}:{token:string;cupId:number;accountId:number;isPlatformOwner:boolean}){
 const [data,setData]=useState<AccessPayload|null>(null),[activity,setActivity]=useState<Activity[]>([]),[email,setEmail]=useState(""),[name,setName]=useState(""),[role,setRole]=useState<"admin"|"owner">("admin"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[credentials,setCredentials]=useState<{email:string;password:string}|null>(null);
 const [credentialsCopied,setCredentialsCopied]=useState(false);
 const [currentPassword,setCurrentPassword]=useState(""),[newPassword,setNewPassword]=useState("");
 const load=useCallback(async()=>{const [access,events]=await Promise.all([req<AccessPayload>(`/api/admin/cups/${cupId}/members`,token),req<{activity:Activity[]}>(`/api/admin/cups/${cupId}/activity`,token)]);setData(access);setActivity(events.activity||[]);},[token,cupId]);
 useEffect(()=>{setError("");setMessage("");setCredentials(null);void load().catch(e=>setError(e instanceof Error?e.message:"Åtkomsten kunde inte hämtas."));},[load]);
 async function add(event:FormEvent){event.preventDefault();setBusy(true);setError("");setMessage("");setCredentials(null);setCredentialsCopied(false);try{const result=await req<MemberResult>(`/api/admin/cups/${cupId}/members`,token,{method:"POST",body:JSON.stringify({email,display_name:name||null,role})});if(result.temporary_password)setCredentials({email:result.member.email,password:result.temporary_password});setEmail("");setName("");setRole("admin");setMessage(result.email_status==="sent"?`${result.member.email} har fått åtkomst och inloggningsuppgifterna har mejlats.`:`${result.member.email} har fått åtkomst, men inget mejl skickades. Kopiera uppgifterna nedan.`);await load();}catch(e){setError(e instanceof Error?e.message:"Administratören kunde inte läggas till.");}finally{setBusy(false);}}
 async function copyCredentials(){if(!credentials)return;await navigator.clipboard.writeText(`CupNavi lokal admin\nE-post: ${credentials.email}\nTillfälligt lösenord: ${credentials.password}\nLogga in: ${window.location.origin}/admin`);setCredentialsCopied(true);}
 async function changeRole(member:Member,nextRole:"owner"|"admin"){setBusy(true);setError("");try{await req(`/api/admin/cups/${cupId}/members/${member.id}`,token,{method:"PUT",body:JSON.stringify({role:nextRole})});setMessage(`Rollen för ${member.email} uppdaterades.`);await load();}catch(e){setError(e instanceof Error?e.message:"Rollen kunde inte ändras.");}finally{setBusy(false);}}
 async function remove(member:Member){if(!window.confirm(`Ta bort ${member.email} från cupen?`))return;setBusy(true);setError("");try{await req(`/api/admin/cups/${cupId}/members/${member.id}`,token,{method:"DELETE"});setMessage(`${member.email} har inte längre åtkomst.`);await load();}catch(e){setError(e instanceof Error?e.message:"Åtkomsten kunde inte tas bort.");}finally{setBusy(false);}}
 async function updatePassword(event:FormEvent){event.preventDefault();setBusy(true);setError("");try{const result=await req<{changed:boolean;token:string}>("/api/admin/account/password",token,{method:"PUT",body:JSON.stringify({current_password:currentPassword,new_password:newPassword})});localStorage.setItem("cupnavi_admin_session_v629",result.token);window.dispatchEvent(new Event("cupnavi:session-refresh"));setCurrentPassword("");setNewPassword("");setMessage("Lösenordet är ändrat och övriga sessioner har loggats ut.");}catch(e){setError(e instanceof Error?e.message:"Lösenordet kunde inte ändras.");}finally{setBusy(false);}}
 const canManage=Boolean(data?.can_manage);
 return <section className="admin-panel admin-teams" id="access"><div className="admin-panel__top"><span>ÅTKOMST / LOKAL ADMIN</span><strong>{data?.current_role?.toUpperCase()||"LADDAR"}</strong></div><div className="admin-cupinfo__head"><div><h2>Lokal admin</h2><p>Ge en person ett eget konto för just den här cupen. En lokal admin kan administrera cupen och korrigera resultat, men får inte åtkomst till andra cuper.</p></div><span className="admin-lock">CUPBEGRÄNSAD</span></div>
 {(error||message)&&<div className="admin-code-placeholder" style={{marginTop:16}}><b>{error?"Fel":"Klart"}</b><span>{error||message}</span></div>}
 {canManage&&<form onSubmit={add} className="admin-team-editor"><div className="admin-form-grid"><label>Namn<input value={name} onChange={e=>setName(e.target.value)} placeholder="För- och efternamn"/></label><label>E-post<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Roll<select value={role} onChange={e=>setRole(e.target.value as "admin"|"owner")}><option value="admin">Lokal admin – redigerar denna cup</option><option value="owner">Cupägare – hanterar även lokala admins</option></select></label></div><div className="admin-form-footer"><span>Nya konton får ett tillfälligt lösenord som bara visas en gång.</span><button disabled={busy||!email.trim()}>{busy?"Sparar…":"Lägg till lokal admin"}</button></div></form>}
 {credentials&&<div className="admin-access-credentials"><strong>Tillfälliga inloggningsuppgifter</strong><p><b>Inget mejl skickas automatiskt.</b> Kopiera uppgifterna och skicka dem säkert till personen. Lösenordet visas inte igen.</p><code>E-post: {credentials.email}<br/>Lösenord: {credentials.password}</code><button type="button" onClick={()=>void copyCredentials()}>{credentialsCopied?"Uppgifterna kopierade ✓":"Kopiera inloggningsuppgifter"}</button></div>}
 <div className="admin-team-list admin-access-members" style={{marginTop:16}}>{(data?.members||[]).map(member=><article key={member.id}><div className="admin-access-member__identity"><strong>{member.display_name||member.email}</strong><small>{member.email}</small><span>{member.role==="owner"?"Cupägare":"Lokal admin"}</span></div>{canManage&&<div className="admin-team-actions"><select aria-label={`Roll för ${member.email}`} disabled={busy} value={member.role} onChange={e=>void changeRole(member,e.target.value as "owner"|"admin")}><option value="owner">Cupägare</option><option value="admin">Lokal admin</option></select><button type="button" disabled={busy||member.id===accountId} onClick={()=>void remove(member)}>Ta bort</button></div>}</article>)}</div>
 {!isPlatformOwner&&<form onSubmit={updatePassword} className="admin-team-editor"><h3>Byt mitt lösenord</h3><div className="admin-form-grid"><label>Nuvarande lösenord<input type="password" required value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)}/></label><label>Nytt lösenord<input type="password" required minLength={10} value={newPassword} onChange={e=>setNewPassword(e.target.value)}/><small>Minst 10 tecken.</small></label></div><div className="admin-form-footer"><span>Byt direkt om du fått ett tillfälligt lösenord.</span><button disabled={busy||newPassword.length<10}>Byt lösenord</button></div></form>}
 <div className="admin-panel__top" style={{marginTop:24}}><span>SENASTE AKTIVITET</span><strong>{activity.length}</strong></div><div className="admin-team-list admin-access-activity">{activity.length?activity.map(item=><article key={item.id}><div><strong>{item.summary.replace(/ som admin$/i," som lokal admin")}</strong><small>Utfört av {item.actor_email}</small><time>{String(item.created_at).replace("T"," ").slice(0,16)}</time></div></article>):<div className="admin-empty"><strong>Ingen aktivitet ännu</strong><span>Nya ändringar visas här.</span></div>}</div>
 </section>;
}
