"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { CLIENT_API_BASE } from "../lib/client-api";

type Member={id:number;email:string;display_name?:string|null;role:"owner"|"admin";created_at?:string|null};
type Activity={id:number;actor_email:string;summary:string;created_at:string};
type AccessPayload={members:Member[];current_role:string;can_manage:boolean};

async function req<T>(path:string,token:string,options:RequestInit={}):Promise<T>{
 const headers=new Headers(options.headers||{});headers.set("Authorization",`Bearer ${token}`);if(options.body)headers.set("Content-Type","application/json");
 const response=await fetch(`${CLIENT_API_BASE}${path}`,{...options,headers,cache:"no-store"});const payload=await response.json().catch(()=>null);
 if(!response.ok)throw new Error(payload?.detail||`API-fel ${response.status}`);return payload as T;
}

export default function AccessAdmin({token,cupId,accountId,isPlatformOwner}:{token:string;cupId:number;accountId:number;isPlatformOwner:boolean}){
 const [data,setData]=useState<AccessPayload|null>(null),[activity,setActivity]=useState<Activity[]>([]),[email,setEmail]=useState(""),[name,setName]=useState(""),[role,setRole]=useState<"admin"|"owner">("admin"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[credentials,setCredentials]=useState<{email:string;password:string}|null>(null);
 const [currentPassword,setCurrentPassword]=useState(""),[newPassword,setNewPassword]=useState("");
 const load=useCallback(async()=>{const [access,events]=await Promise.all([req<AccessPayload>(`/api/admin/cups/${cupId}/members`,token),req<{activity:Activity[]}>(`/api/admin/cups/${cupId}/activity`,token)]);setData(access);setActivity(events.activity||[]);},[token,cupId]);
 useEffect(()=>{setError("");setMessage("");setCredentials(null);void load().catch(e=>setError(e instanceof Error?e.message:"Åtkomsten kunde inte hämtas."));},[load]);
 async function add(event:FormEvent){event.preventDefault();setBusy(true);setError("");setMessage("");setCredentials(null);try{const result=await req<{member:Member;temporary_password?:string|null}>(`/api/admin/cups/${cupId}/members`,token,{method:"POST",body:JSON.stringify({email,display_name:name||null,role})});if(result.temporary_password)setCredentials({email:result.member.email,password:result.temporary_password});setEmail("");setName("");setRole("admin");setMessage(`${result.member.email} har fått åtkomst.`);await load();}catch(e){setError(e instanceof Error?e.message:"Administratören kunde inte läggas till.");}finally{setBusy(false);}}
 async function changeRole(member:Member,nextRole:"owner"|"admin"){setBusy(true);setError("");try{await req(`/api/admin/cups/${cupId}/members/${member.id}`,token,{method:"PUT",body:JSON.stringify({role:nextRole})});setMessage(`Rollen för ${member.email} uppdaterades.`);await load();}catch(e){setError(e instanceof Error?e.message:"Rollen kunde inte ändras.");}finally{setBusy(false);}}
 async function remove(member:Member){if(!window.confirm(`Ta bort ${member.email} från cupen?`))return;setBusy(true);setError("");try{await req(`/api/admin/cups/${cupId}/members/${member.id}`,token,{method:"DELETE"});setMessage(`${member.email} har inte längre åtkomst.`);await load();}catch(e){setError(e instanceof Error?e.message:"Åtkomsten kunde inte tas bort.");}finally{setBusy(false);}}
 async function updatePassword(event:FormEvent){event.preventDefault();setBusy(true);setError("");try{const result=await req<{changed:boolean;token:string}>("/api/admin/account/password",token,{method:"PUT",body:JSON.stringify({current_password:currentPassword,new_password:newPassword})});localStorage.setItem("cupnavi_admin_session_v629",result.token);window.dispatchEvent(new Event("cupnavi:session-refresh"));setCurrentPassword("");setNewPassword("");setMessage("Lösenordet är ändrat och övriga sessioner har loggats ut.");}catch(e){setError(e instanceof Error?e.message:"Lösenordet kunde inte ändras.");}finally{setBusy(false);}}
 const canManage=Boolean(data?.can_manage);
 return <section className="admin-panel admin-teams" id="access"><div className="admin-panel__top"><span>ÅTKOMST</span><strong>{data?.current_role?.toUpperCase()||"LADDAR"}</strong></div><div className="admin-cupinfo__head"><div><h2>Användare och roller</h2><p>Varje person använder ett eget konto. Ägare hanterar åtkomst; administratörer arbetar med cupens innehåll.</p></div><span className="admin-lock">PERSONLIGA KONTON</span></div>
 {(error||message)&&<div className="admin-code-placeholder" style={{marginTop:16}}><b>{error?"Fel":"Klart"}</b><span>{error||message}</span></div>}
 {canManage&&<form onSubmit={add} className="admin-team-editor"><div className="admin-form-grid"><label>Namn<input value={name} onChange={e=>setName(e.target.value)} placeholder="För- och efternamn"/></label><label>E-post<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Roll<select value={role} onChange={e=>setRole(e.target.value as "admin"|"owner")}><option value="admin">Administratör – redigerar cupen</option><option value="owner">Ägare – hanterar även användare</option></select></label></div><div className="admin-form-footer"><span>Nya konton får ett tillfälligt lösenord som bara visas en gång.</span><button disabled={busy||!email.trim()}>{busy?"Sparar…":"Lägg till användare"}</button></div></form>}
 {credentials&&<div className="admin-panel" style={{marginTop:14,background:"#fff1a8"}}><strong>Tillfälliga inloggningsuppgifter</strong><p>Skicka uppgifterna säkert. Lösenordet visas inte igen.</p><code style={{display:"block",padding:12}}>E-post: {credentials.email}<br/>Lösenord: {credentials.password}</code></div>}
 <div className="admin-team-list" style={{marginTop:16}}>{(data?.members||[]).map(member=><article key={member.id}><div><strong>{member.display_name||member.email}</strong><small>{member.email} · {member.role==="owner"?"Ägare":"Administratör"}</small></div>{canManage&&<div className="admin-team-actions"><select aria-label={`Roll för ${member.email}`} disabled={busy} value={member.role} onChange={e=>void changeRole(member,e.target.value as "owner"|"admin")}><option value="owner">Ägare</option><option value="admin">Administratör</option></select><button type="button" disabled={busy||member.id===accountId} onClick={()=>void remove(member)}>Ta bort</button></div>}</article>)}</div>
 {!isPlatformOwner&&<form onSubmit={updatePassword} className="admin-team-editor"><h3>Byt mitt lösenord</h3><div className="admin-form-grid"><label>Nuvarande lösenord<input type="password" required value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)}/></label><label>Nytt lösenord<input type="password" required minLength={10} value={newPassword} onChange={e=>setNewPassword(e.target.value)}/><small>Minst 10 tecken.</small></label></div><div className="admin-form-footer"><span>Byt direkt om du fått ett tillfälligt lösenord.</span><button disabled={busy||newPassword.length<10}>Byt lösenord</button></div></form>}
 <div className="admin-panel__top" style={{marginTop:24}}><span>SENASTE AKTIVITET</span><strong>{activity.length}</strong></div><div className="admin-team-list">{activity.length?activity.map(item=><article key={item.id}><div><strong>{item.summary}</strong><small>{item.actor_email} · {String(item.created_at).replace("T"," ")}</small></div></article>):<div className="admin-empty"><strong>Ingen aktivitet ännu</strong><span>Nya ändringar visas här.</span></div>}</div>
 </section>;
}
