"use client";

import { ChangeEvent, useState } from "react";
import { CLIENT_API_BASE } from "../lib/client-api";

const API=CLIENT_API_BASE;
type Row={row:number;name:string;age_class?:string|null;group?:string|null;group_id?:number|null;primary_color:string;secondary_color:string;errors:string[];warnings:string[];valid:boolean};
type Preview={filename:string;rows:Row[];valid_count:number;error_count:number};

export default function ImportAdmin({token,cupId,onImported}:{token:string;cupId:number;onImported?:()=>void|Promise<void>}){
 const[preview,setPreview]=useState<Preview|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[message,setMessage]=useState("");
 async function choose(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;setBusy(true);setError("");setMessage("");setPreview(null);try{const form=new FormData();form.append("file",file);const response=await fetch(`${API}/api/admin/cups/${cupId}/import/teams/preview`,{method:"POST",headers:{Authorization:`Bearer ${token}`},body:form,cache:"no-store"});const payload=await response.json().catch(()=>null);if(!response.ok)throw new Error(payload?.detail||`API-fel ${response.status}`);setPreview(payload)}catch(err){setError(err instanceof Error?err.message:"Filen kunde inte läsas") }finally{setBusy(false);event.target.value="";}}
 async function commit(){if(!preview||preview.error_count||!preview.valid_count)return;setBusy(true);setError("");setMessage("");try{const rows=preview.rows.map(r=>({name:r.name,age_class:r.age_class,group_id:r.group_id,primary_color:r.primary_color,secondary_color:r.secondary_color}));const response=await fetch(`${API}/api/admin/cups/${cupId}/import/teams/commit`,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({rows}),cache:"no-store"});const payload=await response.json().catch(()=>null);if(!response.ok)throw new Error(payload?.detail||`API-fel ${response.status}`);setMessage(`${payload.imported} lag importerades.`);setPreview(null);await onImported?.()}catch(err){setError(err instanceof Error?err.message:"Importen misslyckades")}finally{setBusy(false)}}
 return <><style jsx global>{`.admin-module-grid{display:none!important}`}</style><section className="admin-panel admin-teams" id="import"><div className="admin-panel__top"><span>12 / IMPORT</span><strong>CSV · XLSX</strong></div><div className="admin-cupinfo__head"><div><h2>Importera lag</h2><p>Läs in en CSV- eller XLSX-fil. CupNavi visar alltid en förhandsgranskning och skriver inget förrän alla rader är giltiga.</p></div><span className="admin-lock">INGEN TYST ÖVERSKRIVNING</span></div><div className="admin-team-editor"><label>Välj fil<input type="file" accept=".csv,.xlsx,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={choose} disabled={busy}/></label><small>Kolumner som känns igen: Lag/Lagnamn, Åldersklass, Grupp, Primärfärg och Sekundärfärg. Befintliga lag och okända grupper stoppas.</small></div>{(error||message)&&<div className="admin-code-placeholder" style={{marginTop:16}}><b>{error?"Fel":"Klart"}</b> · {error||message}</div>}{preview&&<><div className="admin-panel__top" style={{marginTop:18}}><span>{preview.filename}</span><strong>{preview.valid_count} KLARA · {preview.error_count} FEL</strong></div><div className="admin-team-list">{preview.rows.map(row=><article key={row.row}><div><strong>Rad {row.row}: {row.name||"Namnlöst lag"}</strong><small>{[row.age_class,row.group].filter(Boolean).join(" · ")||"Ingen klass/grupp"}</small>{row.errors.length>0&&<small style={{display:"block"}}>Fel: {row.errors.join(" · ")}</small>}</div><strong>{row.valid?"OK":"STOPP"}</strong></article>)}</div><div className="admin-form-footer"><span>{preview.error_count?"Rätta filen och ladda upp igen. Ingenting har skrivits.":"Alla rader är validerade och redo."}</span><button type="button" disabled={busy||preview.error_count>0||preview.valid_count===0} onClick={commit}>{busy?"Importerar…":`Importera ${preview.valid_count} lag`}</button></div></>}</section></>;
}
