"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import PublishReportingAdmin from "./publish-reporting-admin";
import ImportAdmin from "./import-admin";
import { CLIENT_API_BASE } from "../lib/client-api";

const API_BASE=CLIENT_API_BASE;
type Participant={source:string;kind:string;resolved:boolean;team_id?:number|null;team_name?:string|null;reason?:string};
type Match={id:number;stage:string;round_no?:number|null;match_no?:number|null;home_source?:string|null;away_source?:string|null;home_participant?:Participant;away_participant?:Participant;home_team_name?:string|null;away_team_name?:string|null;scheduled_start?:string|null;pitch_number?:number|null;home_score?:number|null;away_score?:number|null};
type Bracket={id:number;name:string;size:number;bronze_match:number|boolean;matches:Match[]};
type BracketIssue={code:string;message:string;match_id?:number|null;source?:string};
type BracketValidation={ready:boolean;issue_count:number;issues:BracketIssue[];playoff_match_count:number;skipped?:boolean};
type Payload={playoff_format:string;bronze_match:boolean;playoff_tie_rule:string;playoff_extra_time_minutes:number;brackets:Bracket[];bracket_count:number;match_count:number;played_count:number;locked_count:number;structure_locked:boolean;bracket_ready:boolean;bracket_validation:BracketValidation};
async function api<T>(path:string,options:RequestInit,token:string):Promise<T>{const headers=new Headers(options.headers||{});if(options.body)headers.set("Content-Type","application/json");headers.set("Authorization",`Bearer ${token}`);const response=await fetch(`${API_BASE}${path}`,{...options,headers,cache:"no-store"});const payload=await response.json().catch(()=>null);if(!response.ok)throw new Error(payload?.detail||`API-fel ${response.status}`);return payload as T;}
function sourceLabel(source?:string|null){if(!source)return"Ej satt";const parts=source.split(":");if(parts[0]==="group"&&parts.length>=3){const p=Number(parts[2]);const rank=p===1?"1:a":p===2?"2:a":p===3?"3:a":`${parts[2]}:a`;return `${rank} i grupp ${parts[1]}`;}if(parts[0]==="winner")return `Vinnare match ${parts[1]}`;if(parts[0]==="loser")return `Förlorare match ${parts[1]}`;if(parts[0]==="team")return `Lag ${parts[1]}`;return source.replaceAll(":"," ");}
function participantLabel(match:Match,side:"home"|"away"){const direct=side==="home"?match.home_team_name:match.away_team_name;const participant=side==="home"?match.home_participant:match.away_participant;const source=side==="home"?match.home_source:match.away_source;return direct||participant?.team_name||sourceLabel(source);}
export default function PlayoffAdmin({token,cupId}:{token:string;cupId:number}){
 const[data,setData]=useState<Payload|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[message,setMessage]=useState("");const[exportBusy,setExportBusy]=useState(false);const[exportError,setExportError]=useState("");
 const load=useCallback(async()=>{setBusy(true);setError("");try{setData(await api<Payload>(`/api/admin/cups/${cupId}/playoffs`,{},token));}catch(err){setError(err instanceof Error?err.message:"Slutspelet kunde inte hämtas.");}finally{setBusy(false);}},[cupId,token]);useEffect(()=>{void load();},[load]);
 async function save(e:FormEvent){e.preventDefault();if(!data)return;setBusy(true);setError("");setMessage("");try{setData(await api<Payload>(`/api/admin/cups/${cupId}/playoffs`,{method:"PUT",body:JSON.stringify({playoff_format:data.playoff_format,bronze_match:data.bronze_match,playoff_tie_rule:data.playoff_tie_rule,playoff_extra_time_minutes:data.playoff_extra_time_minutes})},token));setMessage("Slutspelsinställningarna är sparade. Cupen är avpublicerad tills ändringen har kontrollerats.");}catch(err){setError(err instanceof Error?err.message:"Slutspelsinställningarna kunde inte sparas.");}finally{setBusy(false);}}
 async function downloadPdf(){setExportBusy(true);setExportError("");try{const response=await fetch(`${API_BASE}/api/admin/cups/${cupId}/export/pdf`,{headers:{Authorization:`Bearer ${token}`},cache:"no-store"});if(!response.ok){const payload=await response.json().catch(()=>null);throw new Error(payload?.detail||`API-fel ${response.status}`);}const blob=await response.blob();const disposition=response.headers.get("Content-Disposition")||"";const match=disposition.match(/filename\*=UTF-8''([^;]+)/i);const filename=match?decodeURIComponent(match[1]):`cupnavi-cup-${cupId}.pdf`;const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download=filename;document.body.appendChild(anchor);anchor.click();anchor.remove();URL.revokeObjectURL(url);}catch(err){setExportError(err instanceof Error?err.message:"PDF-exporten misslyckades.");}finally{setExportBusy(false);}}
 const tail=<><PublishReportingAdmin token={token} cupId={cupId}/><ImportAdmin token={token} cupId={cupId} onImported={()=>window.location.reload()}/><ExportPanel busy={exportBusy} error={exportError} download={downloadPdf}/></>;
 if(!data)return <><section className="admin-panel admin-teams" id="playoffs"><div className="admin-panel__top"><span>09 / SLUTSPEL</span><strong>{busy?"HÄMTAR":"SAKNAS"}</strong></div><h2>Slutspel</h2><p>{error||"Hämtar slutspelsdata…"}</p></section>{tail}</>;
 const validation=data.bracket_validation;
 return <><section className="admin-panel admin-teams" id="playoffs"><div className="admin-panel__top"><span>09 / SLUTSPEL</span><strong>{data.bracket_ready?"TRÄDET ÄR KONTROLLERAT":`${validation.issue_count} FEL I TRÄDET`}</strong></div><div className="admin-cupinfo__head"><div><h2>Slutspel</h2><p>Redigera grundreglerna och inspektera det slutspel som faktiskt är sparat. Befintliga träd skrivs aldrig över automatiskt.</p></div><span className="admin-lock">HISTORIKSKYDD</span></div>{(error||message)&&<div className="admin-code-placeholder" style={{marginBottom:16}}><b>{error?"Fel":"Klart"}</b> · {error||message}</div>}{data.structure_locked&&<div className="admin-code-placeholder" style={{marginBottom:16}}><b>Strukturen är låst</b> · {data.match_count} slutspelsmatcher finns redan. Format och bronsmatch kan därför inte ändras här.</div>}
 {!validation.skipped&&<div className="admin-code-placeholder" style={{marginBottom:16}}>{data.bracket_ready?<><b>Slutspelsträdet är strukturellt komplett</b> · Alla sparade deltagarkällor pekar på giltiga lag, grupper eller tidigare matcher och inga cirkulära beroenden hittades.</>:<><b>Slutspelsträdet måste rättas före publicering</b><div style={{display:"grid",gap:6,marginTop:8}}>{validation.issues.map((issue,index)=><span key={`${issue.code}-${issue.match_id||0}-${index}`}>• {issue.message}</span>)}</div></>}</div>}
 <form className="admin-team-editor" onSubmit={save}><div className="admin-form-grid"><label>Slutspelsformat<select disabled={data.structure_locked} value={data.playoff_format} onChange={e=>setData({...data,playoff_format:e.target.value})}><option>Inget slutspel</option><option>Slutspel – bara ettor och tvåor</option><option>A- och B-slutspel</option><option>Placeringsslutspel – ettor mot ettor osv.</option><option>Manuellt slutspel</option></select></label><label>Avgörande vid oavgjort<select disabled={data.played_count>0} value={data.playoff_tie_rule} onChange={e=>setData({...data,playoff_tie_rule:e.target.value})}><option>Straffar direkt</option><option>Förlängning + straffar</option></select></label>{data.playoff_tie_rule==="Förlängning + straffar"&&<label>Förlängning, minuter<input type="number" min={0} max={60} disabled={data.played_count>0} value={data.playoff_extra_time_minutes} onChange={e=>setData({...data,playoff_extra_time_minutes:Number(e.target.value)})}/></label>}<label style={{display:"flex",alignItems:"center",gap:10}}><input type="checkbox" disabled={data.structure_locked} checked={data.bronze_match} onChange={e=>setData({...data,bronze_match:e.target.checked})}/> Bronsmatch</label></div><div className="admin-form-footer"><span>{data.played_count?`${data.played_count} slutspelsmatcher är färdigspelade.`:"Inga färdigspelade slutspelsmatcher ännu."}</span><button type="submit" disabled={busy}>{busy?"Sparar…":"Spara slutspelsregler"}</button></div></form>
 <h3 style={{marginTop:22}}>Sparade slutspelsträd</h3>{data.brackets.length?<div className="admin-team-list">{data.brackets.map(b=><article key={b.id} style={{display:"block"}}><div><strong>{b.name}</strong><small>{b.size} platser · {b.matches.length} matcher{b.bronze_match?" · bronsmatch":""}</small></div><div className="admin-team-list" style={{marginTop:12}}>{b.matches.map(m=><article key={m.id}><div><strong>{participantLabel(m,"home")} – {participantLabel(m,"away")}</strong><small>{m.stage}{m.round_no?` · omgång ${m.round_no}`:""}{m.match_no?` · match ${m.match_no}`:""}{m.scheduled_start?` · ${m.scheduled_start.replace("T"," ")}`:""}</small></div><strong>{m.home_score==null||m.away_score==null?"–":`${m.home_score}–${m.away_score}`}</strong></article>)}</div></article>)}</div>:<div className="admin-empty"><strong>Inget slutspelsträd skapat</strong><span>Inställningarna kan sparas nu. Själva genereringen kopplas mot CupNavis befintliga slutspelsmotor i nästa fördjupning.</span></div>}
 </section>{tail}</>;
}
function ExportPanel({busy,error,download}:{busy:boolean;error:string;download:()=>void}){return <section className="admin-panel admin-teams" id="export"><div className="admin-panel__top"><span>13 / PDF & EXPORT</span><strong>AKTIV</strong></div><div className="admin-cupinfo__head"><div><h2>Cupdokument</h2><p>Skapa en färsk PDF från CupNavis riktiga cupdata. Dokumentet innehåller cupinfo, grupper och lag, planer samt spelschema och resultat.</p></div><span className="admin-lock">SERVERGENERERAD</span></div>{error&&<div className="admin-code-placeholder" style={{marginBottom:16}}><b>Fel</b> · {error}</div>}<div className="admin-form-footer"><span>PDF:en genereras vid klick och cachelagras inte.</span><button type="button" onClick={download} disabled={busy}>{busy?"Skapar PDF…":"Ladda ner cup-PDF"}</button></div></section>}
