"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";

const API_BASE=(process.env.NEXT_PUBLIC_CUPNAVI_API_BASE||"http://localhost:8000").replace(/\/$/,"");
type Match={id:number;stage:string;round_no?:number|null;match_no?:number|null;home_source?:string|null;away_source?:string|null;scheduled_start?:string|null;pitch_number?:number|null;home_score?:number|null;away_score?:number|null};
type Bracket={id:number;name:string;size:number;bronze_match:number|boolean;matches:Match[]};
type Payload={playoff_format:string;bronze_match:boolean;playoff_tie_rule:string;playoff_extra_time_minutes:number;brackets:Bracket[];bracket_count:number;match_count:number;played_count:number;locked_count:number;structure_locked:boolean};
async function api<T>(path:string,options:RequestInit,token:string):Promise<T>{const headers=new Headers(options.headers||{});if(options.body)headers.set("Content-Type","application/json");headers.set("Authorization",`Bearer ${token}`);const response=await fetch(`${API_BASE}${path}`,{...options,headers,cache:"no-store"});const payload=await response.json().catch(()=>null);if(!response.ok)throw new Error(payload?.detail||`API-fel ${response.status}`);return payload as T;}
export default function PlayoffAdmin({token,cupId}:{token:string;cupId:number}){
 const[data,setData]=useState<Payload|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[message,setMessage]=useState("");
 const load=useCallback(async()=>{setBusy(true);setError("");try{setData(await api<Payload>(`/api/admin/cups/${cupId}/playoffs`,{},token));}catch(err){setError(err instanceof Error?err.message:"Slutspelet kunde inte hämtas.");}finally{setBusy(false);}},[cupId,token]);useEffect(()=>{void load();},[load]);
 async function save(e:FormEvent){e.preventDefault();if(!data)return;setBusy(true);setError("");setMessage("");try{setData(await api<Payload>(`/api/admin/cups/${cupId}/playoffs`,{method:"PUT",body:JSON.stringify({playoff_format:data.playoff_format,bronze_match:data.bronze_match,playoff_tie_rule:data.playoff_tie_rule,playoff_extra_time_minutes:data.playoff_extra_time_minutes})},token));setMessage("Slutspelsinställningarna är sparade. Cupen är avpublicerad tills ändringen har kontrollerats.");}catch(err){setError(err instanceof Error?err.message:"Slutspelsinställningarna kunde inte sparas.");}finally{setBusy(false);}}
 if(!data)return <section className="admin-panel admin-teams" id="playoffs"><div className="admin-panel__top"><span>09 / SLUTSPEL</span><strong>{busy?"HÄMTAR":"SAKNAS"}</strong></div><h2>Slutspel</h2><p>{error||"Hämtar slutspelsdata…"}</p></section>;
 return <section className="admin-panel admin-teams" id="playoffs"><div className="admin-panel__top"><span>09 / SLUTSPEL</span><strong>{data.bracket_count} TRÄD · {data.match_count} MATCHER</strong></div><div className="admin-cupinfo__head"><div><h2>Slutspel</h2><p>Redigera grundreglerna och inspektera det slutspel som faktiskt är sparat. Befintliga träd skrivs aldrig över automatiskt.</p></div><span className="admin-lock">HISTORIKSKYDD</span></div>{(error||message)&&<div className="admin-code-placeholder" style={{marginBottom:16}}><b>{error?"Fel":"Klart"}</b> · {error||message}</div>}{data.structure_locked&&<div className="admin-code-placeholder" style={{marginBottom:16}}><b>Strukturen är låst</b> · {data.match_count} slutspelsmatcher finns redan. Format och bronsmatch kan därför inte ändras här.</div>}
 <form className="admin-team-editor" onSubmit={save}><div className="admin-form-grid"><label>Slutspelsformat<select disabled={data.structure_locked} value={data.playoff_format} onChange={e=>setData({...data,playoff_format:e.target.value})}><option>Inget slutspel</option><option>Slutspel – bara ettor och tvåor</option><option>A- och B-slutspel</option><option>Placeringsslutspel – ettor mot ettor osv.</option><option>Manuellt slutspel</option></select></label><label>Avgörande vid oavgjort<select disabled={data.played_count>0} value={data.playoff_tie_rule} onChange={e=>setData({...data,playoff_tie_rule:e.target.value})}><option>Straffar direkt</option><option>Förlängning + straffar</option></select></label>{data.playoff_tie_rule==="Förlängning + straffar"&&<label>Förlängning, minuter<input type="number" min={0} max={60} disabled={data.played_count>0} value={data.playoff_extra_time_minutes} onChange={e=>setData({...data,playoff_extra_time_minutes:Number(e.target.value)})}/></label>}<label style={{display:"flex",alignItems:"center",gap:10}}><input type="checkbox" disabled={data.structure_locked} checked={data.bronze_match} onChange={e=>setData({...data,bronze_match:e.target.checked})}/> Bronsmatch</label></div><div className="admin-form-footer"><span>{data.played_count?`${data.played_count} slutspelsmatcher är färdigspelade.`:"Inga färdigspelade slutspelsmatcher ännu."}</span><button type="submit" disabled={busy}>{busy?"Sparar…":"Spara slutspelsregler"}</button></div></form>
 <h3 style={{marginTop:22}}>Sparade slutspelsträd</h3>{data.brackets.length?<div className="admin-team-list">{data.brackets.map(b=><article key={b.id} style={{display:"block"}}><div><strong>{b.name}</strong><small>{b.size} platser · {b.matches.length} matcher{b.bronze_match?" · bronsmatch":""}</small></div><div className="admin-team-list" style={{marginTop:12}}>{b.matches.map(m=><article key={m.id}><div><strong>{m.home_source||"Ej satt"} – {m.away_source||"Ej satt"}</strong><small>{m.stage}{m.round_no?` · omgång ${m.round_no}`:""}{m.match_no?` · match ${m.match_no}`:""}{m.scheduled_start?` · ${m.scheduled_start.replace("T"," ")}`:""}</small></div><strong>{m.home_score==null||m.away_score==null?"–":`${m.home_score}–${m.away_score}`}</strong></article>)}</div></article>)}</div>:<div className="admin-empty"><strong>Inget slutspelsträd skapat</strong><span>Inställningarna kan sparas nu. Själva genereringen kopplas mot CupNavis befintliga slutspelsmotor i nästa fördjupning.</span></div>}
 </section>;
}
