"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { CLIENT_API_BASE } from "../lib/client-api";
import styles from "./playoff-admin.module.css";
import { PlacementTables } from "./PlacementTables";
import type { PlacementGroup } from "../lib/types";
const DRAW_RULE="Oavgjort tillåtet – tabell avgör";

const API_BASE=CLIENT_API_BASE;
type Participant={source:string;kind:string;resolved:boolean;team_id?:number|null;team_name?:string|null;reason?:string};
type Match={home_source_label?:string;away_source_label?:string;id:number;stage:string;round_no?:number|null;match_no?:number|null;home_source?:string|null;away_source?:string|null;home_participant?:Participant;away_participant?:Participant;home_team_name?:string|null;away_team_name?:string|null;scheduled_start?:string|null;pitch_number?:number|null;home_score?:number|null;away_score?:number|null};
type Bracket={id:number;name:string;size:number;bronze_match:number|boolean;matches:Match[]};
type BracketIssue={code:string;message:string;match_id?:number|null;source?:string};
type BracketValidation={ready:boolean;issue_count:number;issues:BracketIssue[];playoff_match_count:number;skipped?:boolean};
type Payload={rules_locked?:boolean;placement_mode:boolean;placement_eligible:boolean;placement_groups:PlacementGroup[];playoff_format:string;bronze_match:boolean;playoff_tie_rule:string;playoff_extra_time_minutes:number;brackets:Bracket[];bracket_count:number;match_count:number;played_count:number;locked_count:number;structure_locked:boolean;bracket_ready:boolean;bracket_validation:BracketValidation};
async function api<T>(path:string,options:RequestInit,token:string):Promise<T>{const headers=new Headers(options.headers||{});if(options.body)headers.set("Content-Type","application/json");headers.set("Authorization",`Bearer ${token}`);const response=await fetch(`${API_BASE}${path}`,{...options,headers,cache:"no-store"});const payload=await response.json().catch(()=>null);if(!response.ok)throw new Error(payload?.detail||`API-fel ${response.status}`);return payload as T;}
function sourceLabel(source?:string|null){if(!source)return"Ej satt";const parts=source.split(":");if(parts[0]==="group"&&parts.length>=3){const p=Number(parts[2]);const rank=p===1?"1:a":p===2?"2:a":p===3?"3:a":`${parts[2]}:a`;return `${rank} i grupp ${parts[1]}`;}if(parts[0]==="winner")return `Vinnare match ${parts[1]}`;if(parts[0]==="loser")return `Förlorare match ${parts[1]}`;if(parts[0]==="team")return `Lag ${parts[1]}`;return source.replaceAll(":"," ");}
function participantLabel(match:Match,side:"home"|"away"){const direct=side==="home"?match.home_team_name:match.away_team_name;const participant=side==="home"?match.home_participant:match.away_participant;const source=side==="home"?match.home_source:match.away_source;return direct||participant?.team_name||(side==="home"?match.home_source_label:match.away_source_label)||sourceLabel(source);}
export default function PlayoffAdmin({token,cupId}:{token:string;cupId:number}){
 const[data,setData]=useState<Payload|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[message,setMessage]=useState("");
 const load=useCallback(async()=>{setBusy(true);setError("");try{setData(await api<Payload>(`/api/admin/cups/${cupId}/playoffs`,{},token));}catch(err){setError(err instanceof Error?err.message:"Slutspelet kunde inte hämtas.");}finally{setBusy(false);}},[cupId,token]);useEffect(()=>{void load();},[load]);
 async function save(e:FormEvent){e.preventDefault();if(!data)return;setBusy(true);setError("");setMessage("");try{setData(await api<Payload>(`/api/admin/cups/${cupId}/playoffs`,{method:"PUT",body:JSON.stringify({playoff_format:data.playoff_format,bronze_match:data.bronze_match,playoff_tie_rule:data.playoff_tie_rule,playoff_extra_time_minutes:data.playoff_extra_time_minutes})},token));setMessage("Slutspelsinställningarna är sparade. Cupen är avpublicerad tills ändringen har kontrollerats.");}catch(err){setError(err instanceof Error?err.message:"Slutspelsinställningarna kunde inte sparas.");}finally{setBusy(false);}}
 if(!data)return <section className="admin-panel admin-teams" id="playoffs"><div className="admin-panel__top"><span>07 / SLUTSPEL</span><strong>{busy?"HÄMTAR":"SAKNAS"}</strong></div><h2>Slutspel</h2><p>{error||"Hämtar slutspelsdata…"}</p></section>;
 const validation=data.bracket_validation;
 const drawMode=data.playoff_tie_rule===DRAW_RULE;
 return <section className="admin-panel admin-teams" id="playoffs"><div className="admin-panel__top"><span>07 / SLUTSPEL</span><strong>{data.bracket_ready?"TRÄDET ÄR KONTROLLERAT":`${validation.issue_count} FEL I TRÄDET`}</strong></div><div className="admin-cupinfo__head"><div><h2>Slutspel</h2><p>Redigera grundreglerna och inspektera det slutspel som faktiskt är sparat. Befintliga träd skrivs aldrig över automatiskt.</p></div><span className="admin-lock">HISTORIKSKYDD</span></div>{(error||message)&&<div className="admin-code-placeholder" style={{marginBottom:16}}><b>{error?"Fel":"Klart"}</b> · {error||message}</div>}{data.structure_locked&&<div className="admin-code-placeholder" style={{marginBottom:16}}><b>Strukturen är låst</b> · {data.match_count} slutspelsmatcher finns redan. Format och bronsmatch kan därför inte ändras här.</div>}
 {!validation.skipped&&<div className="admin-code-placeholder" style={{marginBottom:16}}>{data.bracket_ready?<><b>Slutspelsträdet är strukturellt komplett</b> · Alla sparade deltagarkällor pekar på giltiga lag, grupper eller tidigare matcher och inga cirkulära beroenden hittades.</>:<><b>Slutspelsträdet måste rättas före publicering</b><div style={{display:"grid",gap:6,marginTop:8}}>{validation.issues.map((issue,index)=><span key={`${issue.code}-${issue.match_id||0}-${index}`}>• {issue.message}</span>)}</div></>}</div>}
 <form className="admin-team-editor" onSubmit={save}><div className="admin-form-grid"><label>Slutspelsformat{data.placement_mode?<strong>Placeringsgruppspel</strong>:<select disabled={data.structure_locked} value={data.playoff_format} onChange={e=>setData({...data,playoff_format:e.target.value})}><option>Inget slutspel</option><option>Slutspel – bara ettor och tvåor</option><option>A- och B-slutspel</option><option>Placeringsslutspel – ettor mot ettor osv.</option><option>Manuellt slutspel</option></select>}</label><label>Vid oavgjort<select disabled={data.rules_locked??data.played_count>0} value={data.playoff_tie_rule} onChange={e=>setData({...data,playoff_tie_rule:e.target.value})}><option>Straffar direkt</option><option>Förlängning + straffar</option><option>{DRAW_RULE}</option></select></label>{data.playoff_tie_rule==="Förlängning + straffar"&&<label>Förlängning, minuter<input type="number" min={0} max={60} disabled={data.rules_locked??data.played_count>0} value={data.playoff_extra_time_minutes} onChange={e=>setData({...data,playoff_extra_time_minutes:Number(e.target.value)})}/></label>}{!drawMode&&<label style={{display:"flex",alignItems:"center",gap:10}}><input type="checkbox" disabled={data.structure_locked} checked={data.bronze_match} onChange={e=>setData({...data,bronze_match:e.target.checked})}/> Bronsmatch</label>}</div>{drawMode&&<p className={styles.explanation}>Alla matcher får sluta oavgjort. Placeringarna avgörs av poäng och cupens tabellskiljning. Ingen förlängning, inga straffar och ingen separat bronsmatch.</p>}{data.placement_eligible&&!drawMode&&<p className={styles.explanation}>Matchschemat bildar placeringsgrupper. Om de ska avgöras med tabell, välj ”Oavgjort tillåtet – tabell avgör” och spara.</p>}<div className="admin-form-footer"><span>{data.played_count?`${data.played_count} slutspelsmatcher är färdigspelade.`:"Inga färdigspelade slutspelsmatcher ännu."}</span><button type="submit" disabled={busy}>{busy?"Sparar…":"Spara slutspelsregler"}</button></div></form>
 <h3 className={styles.heading}>{data.placement_mode?"Placeringsgrupper och matcher":"Sparade slutspelsträd"}</h3>
 <PlacementTables groups={data.placement_groups||[]}/>
 {data.brackets.length?<div className={styles.brackets}>{data.brackets.map(b=><article className={styles.bracket} key={b.id}>
   <header className={styles.bracketHeader}><strong>{data.placement_mode?"Importerat placeringsgruppspel":b.name}</strong><small>{b.size} {data.placement_mode?"lag":"platser"} · {b.matches.length} matcher{!data.placement_mode&&b.bronze_match?" · bronsmatch":""}</small></header>
   <div className={styles.matches}>{b.matches.map(m=><article className={styles.match} key={m.id}>
     <div className={styles.matchDetails}><strong>{participantLabel(m,"home")} – {participantLabel(m,"away")}</strong><span>{m.stage}{!data.placement_mode&&m.round_no?` · omgång ${m.round_no}`:""}{m.match_no?` · match ${m.match_no}`:""}</span><small>{m.scheduled_start?.replace("T"," ")||"Tid saknas"}{m.pitch_number?` · Plan ${m.pitch_number}`:""}</small></div>
     <strong className={styles.score}>{m.home_score==null||m.away_score==null?"–":`${m.home_score}–${m.away_score}`}</strong>
   </article>)}</div>
 </article>)}</div>:<div className="admin-empty"><strong>Inget slutspelsträd skapat</strong><span>Importera och granska cupens slutspelsmatcher för att se dem här.</span></div>}
 </section>;
}
