"use client";
import {useCallback,useEffect,useState} from "react";
const API=(process.env.NEXT_PUBLIC_CUPNAVI_API_BASE||"http://localhost:8000").replace(/\/$/,"");
async function req(path:string,token:string,init:RequestInit={}){const h=new Headers(init.headers);h.set("Authorization",`Bearer ${token}`);if(init.body)h.set("Content-Type","application/json");const r=await fetch(`${API}${path}`,{...init,headers:h,cache:"no-store"});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error(p?.detail||`API-fel ${r.status}`);return p;}
type M={id:number;stage?:string|null;home_team:string;away_team:string;home_score:number|null;away_score:number|null;home_penalties?:number|null;away_penalties?:number|null;status:string;scheduled_start?:string|null};
type ScheduleConflict={type:string;severity:"error"|"warning";message:string;match_ids?:number[]};
type PublicationPayload={tournament?:{is_published?:boolean};ready:boolean;blockers:string[];schedule_conflict_analysis?:{error_count:number;warning_count:number;conflicts:ScheduleConflict[]}};
export default function PublishReportingAdmin({token,cupId}:{token:string;cupId:number}){const[pub,setPub]=useState<PublicationPayload|null>(null),[matches,setMatches]=useState<M[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(false);const load=useCallback(async()=>{try{const[p,m]=await Promise.all([req(`/api/admin/cups/${cupId}/publication`,token),req(`/api/admin/cups/${cupId}/reporting`,token)]);setPub(p);setMatches(m.matches||[]);setError("")}catch(e){setError(e instanceof Error?e.message:"Kunde inte hämta data")}},[token,cupId]);useEffect(()=>{void load()},[load]);
async function toggle(){setBusy(true);try{setError("");setPub(await req(`/api/admin/cups/${cupId}/publication`,token,{method:"PUT",body:JSON.stringify({published:!pub?.tournament?.is_published})}))}catch(e){setError(e instanceof Error?e.message:"Publicering misslyckades")}finally{setBusy(false)}}
async function save(m:M,h:string,a:string,hp:string,ap:string){setBusy(true);try{setError("");await req(`/api/admin/cups/${cupId}/reporting/matches/${m.id}`,token,{method:"PUT",body:JSON.stringify({home_score:Number(h),away_score:Number(a),home_penalties:hp===""?null:Number(hp),away_penalties:ap===""?null:Number(ap),expected_home_score:m.home_score,expected_away_score:m.away_score,expected_home_penalties:m.home_penalties??null,expected_away_penalties:m.away_penalties??null})});await load()}catch(e){setError(e instanceof Error?e.message:"Resultatet kunde inte sparas")}finally{setBusy(false)}}
const blockers=pub?.blockers??[];
const scheduleErrors=pub?.schedule_conflict_analysis?.conflicts?.filter(x=>x.severity==="error")||[];
const publicationStatus=error|| (scheduleErrors.length>0?`${scheduleErrors.length} blockerande schemafel hittades.`:"Publicering använder aktuell serverdata och kontrollerar schemat på nytt.");
const played=matches.filter(m=>m.status==="played").length;
const awaiting=matches.filter(m=>m.status==="awaiting_decision").length;
return <><section className="admin-panel" id="publish"><div className="admin-panel__top"><span>10 / PUBLICERING</span><strong>{pub?.tournament?.is_published?"LIVE":"UTKAST"}</strong></div><h2>Publicering</h2><p>{pub?.ready?"Cupen klarar publiceringsspärrarna.":"Cupen är inte redo att publiceras."}</p>{blockers.length>0&&<div className="admin-empty">{blockers.map((x:string)=><span key={x}>{x}</span>)}</div>}{scheduleErrors.length>0&&<div className="admin-team-list" style={{marginTop:16}}>{scheduleErrors.map((item,index)=><article key={`${item.type}-${index}`}><div><strong>STOPP · {item.message}</strong><small>{item.type==="round_order"?"Rondordningen i gruppspelet måste rättas innan publicering.":"Schemafelet måste åtgärdas innan publicering."}</small></div></article>)}</div>}<div className="admin-form-footer"><span>{publicationStatus}</span><div className="admin-team-actions">{scheduleErrors.length>0&&<a href="#schedule">Öppna Schema</a>}<button disabled={busy||(!pub?.tournament?.is_published&&!pub?.ready)} onClick={toggle}>{pub?.tournament?.is_published?"Avpublicera":"Publicera cup"}</button></div></div></section><section className="admin-panel" id="reporting"><div className="admin-panel__top"><span>11 / MATCHRAPPORTERING</span><strong>{played}/{matches.length} AVGJORDA{awaiting?` · ${awaiting} VÄNTAR AVGÖRANDE`:""}</strong></div><h2>Rapportera resultat</h2><p>Slutspelsmatcher som slutar lika avgörs med ett komplett straffresultat. Nästa match får deltagarna automatiskt från slutspelsträdet.</p><div className="admin-team-list">{matches.map(m=><MatchRow key={m.id} m={m} busy={busy} save={save}/>)}</div></section></>}
function MatchRow({m,busy,save}:{m:M;busy:boolean;save:(m:M,h:string,a:string,hp:string,ap:string)=>void}){const[h,setH]=useState(m.home_score==null?"":String(m.home_score)),[a,setA]=useState(m.away_score==null?"":String(m.away_score)),[hp,setHp]=useState(m.home_penalties==null?"":String(m.home_penalties)),[ap,setAp]=useState(m.away_penalties==null?"":String(m.away_penalties));const knockout=m.stage!=="Gruppspel";const tied=knockout&&h!==""&&a!==""&&Number(h)===Number(a);return <article style={{display:"block"}}><div style={{display:"flex",justifyContent:"space-between",gap:12}}><div><strong>{m.home_team} – {m.away_team}</strong><small>{m.stage||"Match"} · {m.scheduled_start||"Ej schemalagd"}{m.status==="awaiting_decision"?" · väntar avgörande":""}</small></div><div className="admin-team-actions"><input aria-label="Hemmamål" type="number" min="0" value={h} onChange={e=>setH(e.target.value)} style={{width:64}}/><span>–</span><input aria-label="Bortamål" type="number" min="0" value={a} onChange={e=>setA(e.target.value)} style={{width:64}}/><button disabled={busy||h===""||a===""||(tied&&(hp===""||ap===""))} onClick={()=>save(m,h,a,hp,ap)}>Spara</button></div></div>{tied&&<div className="admin-form-grid" style={{marginTop:10}}><label>Straffar {m.home_team}<input aria-label="Hemmastraffar" type="number" min="0" value={hp} onChange={e=>setHp(e.target.value)}/></label><label>Straffar {m.away_team}<input aria-label="Bortastraffar" type="number" min="0" value={ap} onChange={e=>setAp(e.target.value)}/></label></div>}</article>}
