"use client";
import {useCallback,useEffect,useState} from "react";
const API=(process.env.NEXT_PUBLIC_CUPNAVI_API_BASE||"http://localhost:8000").replace(/\/$/,"");const KEY="cupnavi_admin_session_v629";
async function req(path:string,token:string,init:RequestInit={}){const h=new Headers(init.headers);h.set("Authorization",`Bearer ${token}`);if(init.body)h.set("Content-Type","application/json");const r=await fetch(`${API}${path}`,{...init,headers:h,cache:"no-store"});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error(p?.detail||`API-fel ${r.status}`);return p;}
type M={id:number;home_team:string;away_team:string;home_score:number|null;away_score:number|null;status:string;scheduled_start?:string|null};
export default function PublishReportingAdmin(){const[token,setToken]=useState(""),[cupId,setCupId]=useState<number|null>(null),[pub,setPub]=useState<any>(null),[matches,setMatches]=useState<M[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(false);useEffect(()=>{const t=localStorage.getItem(KEY)||"";if(!t)return;setToken(t);req('/api/admin/session',t).then(s=>setCupId(s.cups?.[0]?.id||null)).catch(()=>{})},[]);const load=useCallback(async()=>{if(!token||!cupId)return;try{const[p,m]=await Promise.all([req(`/api/admin/cups/${cupId}/publication`,token),req(`/api/admin/cups/${cupId}/reporting`,token)]);setPub(p);setMatches(m.matches||[]);setError("")}catch(e){setError(e instanceof Error?e.message:"Kunde inte hämta data")}},[token,cupId]);useEffect(()=>{load()},[load]);if(!token||!cupId)return null;
async function toggle(){setBusy(true);try{setPub(await req(`/api/admin/cups/${cupId}/publication`,token,{method:"PUT",body:JSON.stringify({published:!pub?.tournament?.is_published})}))}catch(e){setError(e instanceof Error?e.message:"Publicering misslyckades")}finally{setBusy(false)}}async function save(m:M,h:string,a:string){setBusy(true);try{await req(`/api/admin/cups/${cupId}/reporting/matches/${m.id}`,token,{method:"PUT",body:JSON.stringify({home_score:Number(h),away_score:Number(a),expected_home_score:m.home_score,expected_away_score:m.away_score})});await load()}catch(e){setError(e instanceof Error?e.message:"Resultatet kunde inte sparas")}finally{setBusy(false)}}
return <main className="admin-main" style={{marginLeft:"min(280px,22vw)"}}><section className="admin-panel" id="publish"><div className="admin-panel__top"><span>10 / PUBLICERING</span><strong>{pub?.tournament?.is_published?"LIVE":"UTKAST"}</strong></div><h2>Publicering</h2><p>{pub?.ready?"Cupen klarar publiceringsspärrarna.":"Cupen är inte redo att publiceras."}</p>{pub?.blockers?.length>0&&<div className="admin-empty">{pub.blockers.map((x:string)=><span key={x}>{x}</span>)}</div>}<div className="admin-form-footer"><span>{error}</span><button disabled={busy||(!pub?.tournament?.is_published&&!pub?.ready)} onClick={toggle}>{pub?.tournament?.is_published?"Avpublicera":"Publicera cup"}</button></div></section><section className="admin-panel" id="reporting"><div className="admin-panel__top"><span>11 / MATCHRAPPORTERING</span><strong>{matches.filter(m=>m.status==="played").length}/{matches.length} SPELADE</strong></div><h2>Rapportera resultat</h2><div className="admin-team-list">{matches.map(m=><MatchRow key={m.id} m={m} busy={busy} save={save}/>)}</div></section></main>}
function MatchRow({m,busy,save}:{m:M;busy:boolean;save:(m:M,h:string,a:string)=>void}){const[h,setH]=useState(m.home_score==null?"":String(m.home_score)),[a,setA]=useState(m.away_score==null?"":String(m.away_score));return <article><div><strong>{m.home_team} – {m.away_team}</strong><small>{m.scheduled_start||"Ej schemalagd"}</small></div><div className="admin-team-actions"><input aria-label="Hemmamål" type="number" min="0" value={h} onChange={e=>setH(e.target.value)} style={{width:64}}/><span>–</span><input aria-label="Bortamål" type="number" min="0" value={a} onChange={e=>setA(e.target.value)} style={{width:64}}/><button disabled={busy||h===""||a===""} onClick={()=>save(m,h,a)}>Spara</button></div></article>}
