"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { CLIENT_API_BASE } from "../lib/client-api";

const API_BASE=CLIENT_API_BASE;
type Referee={id:number;name:string;email?:string|null;phone?:string|null;notes?:string|null;active?:number|boolean;assignment_count:number};
type Match={id:number;stage:string;match_no?:number|null;scheduled_start?:string|null;pitch_number?:number|null;referee_id?:number|null;referee_name?:string|null;home_source?:string|null;away_source?:string|null;played:boolean};
type Payload={available:boolean;reason?:string;referees:Referee[];matches:Match[];supports_assignment:boolean;supported_fields:string[]};
const empty={name:"",email:"",phone:"",notes:"",active:true};
async function api<T>(path:string,options:RequestInit,token:string):Promise<T>{const headers=new Headers(options.headers||{});if(options.body)headers.set("Content-Type","application/json");headers.set("Authorization",`Bearer ${token}`);const response=await fetch(`${API_BASE}${path}`,{...options,headers,cache:"no-store"});const payload=await response.json().catch(()=>null);if(!response.ok)throw new Error(payload?.detail||`API-fel ${response.status}`);return payload as T;}
export default function RefereeAdmin({token,cupId}:{token:string;cupId:number}){
 const[data,setData]=useState<Payload|null>(null);const[draft,setDraft]=useState(empty);const[editing,setEditing]=useState<number|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[message,setMessage]=useState("");
 const load=useCallback(async()=>{setBusy(true);setError("");try{setData(await api<Payload>(`/api/admin/cups/${cupId}/referees`,{},token));}catch(err){setError(err instanceof Error?err.message:"Domarna kunde inte hämtas.");}finally{setBusy(false);}},[cupId,token]);useEffect(()=>{void load();},[load]);
 function begin(r:Referee){setEditing(r.id);setDraft({name:r.name,email:r.email||"",phone:r.phone||"",notes:r.notes||"",active:r.active===undefined?true:Boolean(r.active)});}
 function cancel(){setEditing(null);setDraft(empty);}
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setError("");setMessage("");try{const path=editing?`/api/admin/cups/${cupId}/referees/${editing}`:`/api/admin/cups/${cupId}/referees`;await api(path,{method:editing?"PUT":"POST",body:JSON.stringify(draft)},token);await load();setMessage(editing?"Domaren har uppdaterats.":"Domaren har lagts till.");cancel();}catch(err){setError(err instanceof Error?err.message:"Domaren kunde inte sparas.");}finally{setBusy(false);}}
 async function remove(r:Referee){if(!window.confirm(`Ta bort ${r.name}?`))return;setBusy(true);setError("");try{await api(`/api/admin/cups/${cupId}/referees/${r.id}`,{method:"DELETE"},token);await load();setMessage(`${r.name} har tagits bort.`);}catch(err){setError(err instanceof Error?err.message:"Domaren kunde inte tas bort.");}finally{setBusy(false);}}
 async function assign(match:Match,refereeId:number|null){setBusy(true);setError("");try{setData(await api<Payload>(`/api/admin/cups/${cupId}/referees/matches/${match.id}`,{method:"PUT",body:JSON.stringify({referee_id:refereeId})},token));setMessage("Domartilldelningen är sparad.");}catch(err){setError(err instanceof Error?err.message:"Domaren kunde inte tilldelas.");}finally{setBusy(false);}}
 if(!data)return <section className="admin-panel admin-teams" id="referees"><div className="admin-panel__top"><span>08 / DOMARE</span><strong>{busy?"HÄMTAR":"SAKNAS"}</strong></div><h2>Domare</h2><p>{error||"Hämtar domardata…"}</p></section>;
 if(!data.available)return <section className="admin-panel admin-teams" id="referees"><div className="admin-panel__top"><span>08 / DOMARE</span><strong>SCHEMAKONTROLL</strong></div><h2>Domare</h2><p>{data.reason||"Domarmodellen är inte tillgänglig i denna databas."}</p></section>;
 const supports=(name:string)=>data.supported_fields.includes(name);
 return <section className="admin-panel admin-teams" id="referees"><div className="admin-panel__top"><span>08 / DOMARE</span><strong>{data.referees.length} DOMARE</strong></div><div className="admin-cupinfo__head"><div><h2>Domare</h2><p>Hantera cupens befintliga domarregister och matchtilldelningar utan att skapa en parallell domarmodell.</p></div><span className="admin-lock">SCHEMASÄKER CRUD</span></div>{(error||message)&&<div className="admin-code-placeholder" style={{marginBottom:16}}><b>{error?"Fel":"Klart"}</b> · {error||message}</div>}
 <form className="admin-team-editor" onSubmit={save}><div className="admin-form-grid"><label>Namn<input value={draft.name} required onChange={e=>setDraft({...draft,name:e.target.value})}/></label>{supports("email")&&<label>E-post<input type="email" value={draft.email} onChange={e=>setDraft({...draft,email:e.target.value})}/></label>}{supports("phone")&&<label>Telefon<input value={draft.phone} onChange={e=>setDraft({...draft,phone:e.target.value})}/></label>}{supports("notes")&&<label>Anteckning<input value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label>}</div><div className="admin-form-footer"><span>{editing?"Redigerar befintlig domare.":"Lägg till domare i den aktiva cupen."}</span><div className="admin-team-actions">{editing&&<button type="button" onClick={cancel}>Avbryt</button>}<button type="submit" disabled={busy||!draft.name.trim()}>{editing?"Spara domare":"Lägg till domare"}</button></div></div></form>
 <div className="admin-team-list">{data.referees.map(r=><article key={r.id}><div><strong>{r.name}</strong><small>{r.assignment_count} matchuppdrag{r.email?` · ${r.email}`:""}</small></div><div className="admin-team-actions"><button type="button" onClick={()=>begin(r)}>Redigera</button><button type="button" className="is-danger" disabled={r.assignment_count>0} onClick={()=>remove(r)}>Ta bort</button></div></article>)}</div>
 {data.supports_assignment&&<><h3 style={{marginTop:22}}>Matchtilldelning</h3><div className="admin-team-list">{data.matches.map(m=><article key={m.id}><div><strong>{m.home_source||"?"} – {m.away_source||"?"}</strong><small>{m.stage}{m.match_no?` · match ${m.match_no}`:""}{m.scheduled_start?` · ${m.scheduled_start.replace("T"," ")}`:" · ej schemalagd"}</small></div><label>Domare<select value={m.referee_id??""} disabled={busy||m.played} onChange={e=>assign(m,e.target.value?Number(e.target.value):null)}><option value="">Ej tillsatt</option>{data.referees.map(r=><option value={r.id} key={r.id}>{r.name}</option>)}</select></label></article>)}</div></>}
 </section>;
}
