"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { CLIENT_API_BASE } from "../lib/client-api";

const API_BASE=CLIENT_API_BASE;
type Referee={id:number;name:string;email?:string|null;phone?:string|null;notes?:string|null;active?:number|boolean;assignment_count:number};
type Match={id:number;stage:string;match_no?:number|null;scheduled_start?:string|null;pitch_number?:number|null;referee_id?:number|null;referee_name?:string|null;home_source?:string|null;away_source?:string|null;home_team?:string|null;away_team?:string|null;played:boolean};
type Payload={available:boolean;reason?:string;referees:Referee[];matches:Match[];supports_assignment:boolean;supported_fields:string[]};
type CodeStatus={referees:Array<{id:number;name:string;active:boolean;code_active:boolean;created_at?:string|null;rotated_at?:string|null}>};
const empty={name:"",email:"",phone:"",notes:"",active:true};
async function api<T>(path:string,options:RequestInit,token:string):Promise<T>{const headers=new Headers(options.headers||{});if(options.body)headers.set("Content-Type","application/json");headers.set("Authorization",`Bearer ${token}`);const response=await fetch(`${API_BASE}${path}`,{...options,headers,cache:"no-store"});const payload=await response.json().catch(()=>null);if(!response.ok)throw new Error(payload?.detail||`API-fel ${response.status}`);return payload as T;}
export default function RefereeAdmin({token,cupId,publicSlug}:{token:string;cupId:number;publicSlug?:string|null}){
 const[data,setData]=useState<Payload|null>(null);const[draft,setDraft]=useState(empty);const[editing,setEditing]=useState<number|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[message,setMessage]=useState("");
 const[codeStatus,setCodeStatus]=useState<CodeStatus|null>(null);const[newCodes,setNewCodes]=useState<Record<number,string>>({});const[copied,setCopied]=useState<number|null>(null);
 const base=encodeURIComponent(publicSlug||String(cupId));
 const loadCodes=useCallback(async()=>{try{setCodeStatus(await api<CodeStatus>(`/api/admin/cups/${cupId}/role-codes/referees`,{},token));}catch{/* Older databases can still manage referees without portal codes. */}},[cupId,token]);
 const load=useCallback(async()=>{setBusy(true);setError("");try{setData(await api<Payload>(`/api/admin/cups/${cupId}/referees`,{},token));await loadCodes();}catch(err){setError(err instanceof Error?err.message:"Domarna kunde inte hämtas.");}finally{setBusy(false);}},[cupId,loadCodes,token]);useEffect(()=>{void load();},[load]);
 const codeByReferee=new Map((codeStatus?.referees||[]).map(item=>[item.id,item]));
 function begin(r:Referee){setEditing(r.id);setDraft({name:r.name,email:r.email||"",phone:r.phone||"",notes:r.notes||"",active:r.active===undefined?true:Boolean(r.active)});}
 function cancel(){setEditing(null);setDraft(empty);}
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setError("");setMessage("");try{const path=editing?`/api/admin/cups/${cupId}/referees/${editing}`:`/api/admin/cups/${cupId}/referees`;await api(path,{method:editing?"PUT":"POST",body:JSON.stringify(draft)},token);await load();setMessage(editing?"Domaren har uppdaterats.":"Domaren har lagts till.");cancel();}catch(err){setError(err instanceof Error?err.message:"Domaren kunde inte sparas.");}finally{setBusy(false);}}
 async function remove(r:Referee){if(!window.confirm(`Ta bort ${r.name}?`))return;setBusy(true);setError("");try{await api(`/api/admin/cups/${cupId}/referees/${r.id}`,{method:"DELETE"},token);await load();setMessage(`${r.name} har tagits bort.`);}catch(err){setError(err instanceof Error?err.message:"Domaren kunde inte tas bort.");}finally{setBusy(false);}}
 async function assign(match:Match,refereeId:number|null){setBusy(true);setError("");try{setData(await api<Payload>(`/api/admin/cups/${cupId}/referees/matches/${match.id}`,{method:"PUT",body:JSON.stringify({referee_id:refereeId})},token));setMessage("Domartilldelningen är sparad.");}catch(err){setError(err instanceof Error?err.message:"Domaren kunde inte tilldelas.");}finally{setBusy(false);}}
 async function rotateCode(r:Referee){if(codeByReferee.get(r.id)?.code_active&&!window.confirm(`Skapa ny domarkod för ${r.name}? Den gamla koden slutar fungera direkt.`))return;setBusy(true);setError("");try{const result=await api<{code:string;referee_id:number}>(`/api/admin/cups/${cupId}/role-codes/referees/${r.id}/rotate`,{method:"POST"},token);setNewCodes(current=>({...current,[r.id]:result.code}));setMessage(`Ny domarkod skapad för ${r.name}.`);await loadCodes();}catch(err){setError(err instanceof Error?err.message:"Domarkoden kunde inte skapas.");}finally{setBusy(false);}}
 async function copyLink(r:Referee){const href=`/referee?cup=${base}&referee=${r.id}`;try{await navigator.clipboard.writeText(new URL(href,window.location.origin).toString());setCopied(r.id);window.setTimeout(()=>setCopied(null),2000)}catch{setError("Domarlänken kunde inte kopieras. Öppna domarvyn och kopiera adressen manuellt.")}}
 if(!data)return <section className="admin-panel admin-teams" id="referees"><div className="admin-panel__top"><span>VERKTYG / DOMARE</span><strong>{busy?"HÄMTAR":"SAKNAS"}</strong></div><h2>Domare</h2><p>{error||"Hämtar domardata…"}</p></section>;
 if(!data.available)return <section className="admin-panel admin-teams" id="referees"><div className="admin-panel__top"><span>VERKTYG / DOMARE</span><strong>SCHEMAKONTROLL</strong></div><h2>Domare</h2><p>{data.reason||"Domarmodellen är inte tillgänglig i denna databas."}</p></section>;
 const supports=(name:string)=>data.supported_fields.includes(name);
 return <section className="admin-panel admin-teams" id="referees"><div className="admin-panel__top"><span>VERKTYG / DOMARE</span><strong>{data.referees.length} DOMARE</strong></div><div className="admin-cupinfo__head"><div><h2>Domare</h2><p>Hantera cupens befintliga domarregister och matchtilldelningar utan att skapa en parallell domarmodell.</p></div><span className="admin-lock">SCHEMASÄKER CRUD</span></div>{(error||message)&&<div className="admin-code-placeholder" style={{marginBottom:16}}><b>{error?"Fel":"Klart"}</b> · {error||message}</div>}
 <form className="admin-team-editor" onSubmit={save}><div className="admin-form-grid"><label>Namn<input value={draft.name} required onChange={e=>setDraft({...draft,name:e.target.value})}/></label>{supports("email")&&<label>E-post<input type="email" value={draft.email} onChange={e=>setDraft({...draft,email:e.target.value})}/></label>}{supports("phone")&&<label>Telefon<input value={draft.phone} onChange={e=>setDraft({...draft,phone:e.target.value})}/></label>}{supports("notes")&&<label>Anteckning<input value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label>}</div><div className="admin-form-footer"><span>{editing?"Redigerar befintlig domare.":"Lägg till domare i den aktiva cupen."}</span><div className="admin-team-actions">{editing&&<button type="button" onClick={cancel}>Avbryt</button>}<button type="submit" disabled={busy||!draft.name.trim()}>{editing?"Spara domare":"Lägg till domare"}</button></div></div></form>
 <div className="admin-team-list">{data.referees.map(r=>{const status=codeByReferee.get(r.id),href=`/referee?cup=${base}&referee=${r.id}`;return <article key={r.id}><div><strong>{r.name}</strong><small>{r.assignment_count} matchuppdrag{r.email?` · ${r.email}`:""} · {status?.code_active?"domarkod aktiv":"ingen domarkod"}</small>{newCodes[r.id]&&<div className="admin-code-placeholder" style={{marginTop:8,textAlign:"center"}}><small>NY DOMARKOD · VISAS NU</small><div style={{fontSize:"1.7rem",fontWeight:900,letterSpacing:".22em"}}>{newCodes[r.id]}</div><small>Kopiera koden nu. Den går inte att läsa tillbaka senare.</small></div>}</div><div className="admin-team-actions"><a href={href} target="_blank" rel="noreferrer">Öppna domarvy ↗</a><button type="button" onClick={()=>void copyLink(r)}>{copied===r.id?"Länk kopierad ✓":"Kopiera länk"}</button><button type="button" disabled={busy} onClick={()=>void rotateCode(r)}>{status?.code_active?"Regenerera kod":"Generera kod"}</button><button type="button" onClick={()=>begin(r)}>Redigera</button><button type="button" className="is-danger" disabled={r.assignment_count>0} onClick={()=>remove(r)}>Ta bort</button></div></article>})}</div>
 {data.supports_assignment&&<><h3 className="referee-assignment-title">Matchtilldelning</h3><div className="admin-team-list referee-assignment-list">{data.matches.map(m=><article key={m.id}><div className="referee-assignment-match"><strong>{m.home_team||m.home_source||"Ej klart"} – {m.away_team||m.away_source||"Ej klart"}</strong><small>{m.stage}{m.match_no?` · match ${m.match_no}`:""}{m.scheduled_start?` · ${m.scheduled_start.replace("T"," ")}`:" · ej schemalagd"}{m.pitch_number?` · plan ${m.pitch_number}`:""}</small></div><label><span>Domare</span><select value={m.referee_id??""} disabled={busy||m.played} onChange={e=>assign(m,e.target.value?Number(e.target.value):null)}><option value="">Ej tillsatt</option>{data.referees.map(r=><option value={r.id} key={r.id}>{r.name}</option>)}</select></label></article>)}</div></>}
 </section>;
}
