"use client";
import {useCallback,useEffect,useState} from "react";
import {CLIENT_API_BASE} from "../lib/client-api";
const API=CLIENT_API_BASE;
type Referee={id:number;name:string;active:boolean;code_active:boolean;rotated_at?:string|null};
type Payload={referees:Referee[]};
async function req<T>(path:string,token:string,init:RequestInit={}):Promise<T>{const h=new Headers(init.headers);h.set("Authorization",`Bearer ${token}`);if(init.body)h.set("Content-Type","application/json");const r=await fetch(`${API}${path}`,{...init,headers:h,cache:"no-store"});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error(p?.detail||`API-fel ${r.status}`);return p as T;}
export default function RefereeRoleCodeAdmin({token,cupId,publicSlug}:{token:string;cupId:number;publicSlug?:string|null}){
 const[data,setData]=useState<Payload|null>(null),[codes,setCodes]=useState<Record<number,string>>({}),[busy,setBusy]=useState<number|null>(null),[error,setError]=useState("");
 const load=useCallback(async()=>{try{setData(await req<Payload>(`/api/admin/cups/${cupId}/role-codes/referees`,token));setError("")}catch(e){setError(e instanceof Error?e.message:"Domarkoderna kunde inte hämtas.")}},[cupId,token]);
 useEffect(()=>{setCodes({});void load()},[load]);
 async function rotate(referee:Referee){if(referee.code_active&&!window.confirm(`Skapa ny kod för ${referee.name}? Den gamla koden och aktiva domarsessioner slutar fungera direkt.`))return;setBusy(referee.id);setError("");try{const r=await req<{code:string}>(`/api/admin/cups/${cupId}/role-codes/referees/${referee.id}/rotate`,token,{method:"POST"});setCodes(current=>({...current,[referee.id]:r.code}));await load()}catch(e){setError(e instanceof Error?e.message:"Domarkoden kunde inte skapas.")}finally{setBusy(null)}}
 const base=publicSlug?encodeURIComponent(publicSlug):String(cupId);
 return <section className="admin-panel" id="referee-codes"><div className="admin-panel__top"><span>BEHÖRIGHET / DOMARE</span><strong>{data?.referees.filter(r=>r.code_active).length||0} KODER</strong></div><div className="admin-cupinfo__head"><div><h2>Domarportal</h2><p>Varje domare får en egen 4-siffrig kod och ser bara sina tilldelade matcher. Koden visas bara när den skapas.</p></div><span className="admin-lock">INDIVIDUELL ROLL</span></div>{error&&<div className="admin-code-placeholder"><b>Fel</b> · {error}</div>}<div className="admin-team-list">{data?.referees.map(r=><article key={r.id}><div><strong>{r.name}</strong><small>{r.code_active?`Kod aktiv${r.rotated_at?` · ändrad ${String(r.rotated_at).replace("T"," ")}`:""}`:"Ingen kod skapad"}{!r.active?" · inaktiv domare":""}</small>{codes[r.id]&&<div className="admin-code-placeholder" style={{marginTop:8,textAlign:"center"}}><small>NY KOD · VISAS NU</small><div style={{fontSize:"1.7rem",fontWeight:900,letterSpacing:".22em"}}>{codes[r.id]}</div></div>}</div><div className="admin-team-actions"><a href={`/referee?cup=${base}&referee=${r.id}`} target="_blank" rel="noreferrer">Öppna domarvy ↗</a><button type="button" disabled={busy!==null||!r.active} onClick={()=>void rotate(r)}>{busy===r.id?"Arbetar…":r.code_active?"Regenerera kod":"Generera kod"}</button></div></article>)}</div>{data&&data.referees.length===0&&<div className="admin-empty"><strong>Inga domare ännu</strong><span>Lägg först till domare under Domare.</span></div>}</section>;
}
