"use client";
import {FormEvent,useCallback,useEffect,useState} from "react";
import {CLIENT_API_BASE} from "../lib/client-api";
const API=CLIENT_API_BASE,KEY="cupnavi_referee_session_v1";
type Cup={id:number;name:string;public_slug?:string|null};
type Referee={id:number;name:string};
type Match={id:number;stage?:string|null;match_no?:number|null;scheduled_start?:string|null;pitch_number?:number|null;home_team:string;away_team:string;home_score?:number|null;away_score?:number|null;played:boolean};
async function call<T>(path:string,token?:string|null,init:RequestInit={}):Promise<T>{const h=new Headers(init.headers);if(token)h.set("Authorization",`Bearer ${token}`);if(init.body)h.set("Content-Type","application/json");const r=await fetch(`${API}${path}`,{...init,headers:h,cache:"no-store"});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error(p?.detail||`API-fel ${r.status}`);return p as T;}
export default function RefereeClient(){
 const[cup,setCup]=useState(""),[refereeId,setRefereeId]=useState(""),[code,setCode]=useState(""),[token,setToken]=useState<string|null>(null),[cupInfo,setCupInfo]=useState<Cup|null>(null),[referee,setReferee]=useState<Referee|null>(null),[matches,setMatches]=useState<Match[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const logout=useCallback(()=>{localStorage.removeItem(KEY);setToken(null);setCupInfo(null);setReferee(null);setMatches([]);setError("")},[]);
 const load=useCallback(async(t:string)=>{const[s,a]=await Promise.all([call<{cup:Cup;referee:Referee}>("/api/referee/session",t),call<{referee:Referee;matches:Match[]}>("/api/referee/assignments",t)]);setCupInfo(s.cup);setReferee(s.referee);setMatches(a.matches||[])},[]);
 useEffect(()=>{const q=new URLSearchParams(window.location.search);const c=q.get("cup"),r=q.get("referee");if(c)setCup(c);if(r)setRefereeId(r);const stored=localStorage.getItem(KEY);if(stored){setToken(stored);void load(stored).catch(()=>logout())}},[load,logout]);
 async function login(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const r=await call<{token:string;cup:Cup;referee:Referee}>("/api/referee/session",null,{method:"POST",body:JSON.stringify({cup,referee_id:Number(refereeId),code})});localStorage.setItem(KEY,r.token);setToken(r.token);setCupInfo(r.cup);setReferee(r.referee);setCode("");await load(r.token)}catch(err){setError(err instanceof Error?err.message:"Inloggningen misslyckades.")}finally{setBusy(false)}}
 if(!token)return <main className="admin-main" style={{maxWidth:680,margin:"24px auto"}}><header className="admin-pagehead"><div><p className="kicker">CN//REFEREE</p><h1>Domarportal</h1><p>Din egen matchlista utan åtkomst till cupadministrationen.</p></div></header><form className="admin-panel" onSubmit={login}><div className="admin-form-grid"><label>Cup<input value={cup} onChange={e=>setCup(e.target.value)} required placeholder="Cupens länk/ID"/></label><label>Domar-ID<input inputMode="numeric" value={refereeId} onChange={e=>setRefereeId(e.target.value.replace(/\D/g,""))} required placeholder="ID"/></label><label>4-siffrig kod<input inputMode="numeric" pattern="[0-9]{4}" maxLength={4} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,"").slice(0,4))} required placeholder="0000"/></label></div>{error&&<p role="alert">{error}</p>}<div className="admin-form-footer"><span>Använd länken och koden du fått av cupadministratören.</span><button disabled={busy||code.length!==4||!refereeId}>{busy?"Kontrollerar…":"Logga in"}</button></div></form></main>;
 return <main className="admin-main" style={{maxWidth:900,margin:"24px auto"}}><header className="admin-pagehead"><div><p className="kicker">CN//REFEREE</p><h1>{referee?.name||"Domare"}</h1><p>{cupInfo?.name||"CupNavi"} · endast dina tilldelade matcher.</p></div><button type="button" onClick={logout}>Logga ut</button></header>{error&&<section className="admin-panel"><strong>Fel</strong><p>{error}</p></section>}<section className="admin-panel admin-teams"><div className="admin-panel__top"><span>MINA MATCHER</span><strong>{matches.length} UPPDRAG</strong></div><div className="admin-team-list">{matches.map(m=><article key={m.id}><div><strong>{m.home_team} – {m.away_team}</strong><small>{m.scheduled_start?.replace("T"," ")||"Ej schemalagd"}{m.pitch_number?` · plan ${m.pitch_number}`:""}{m.stage?` · ${m.stage}`:""}{m.match_no?` · match ${m.match_no}`:""}</small></div><div><strong>{m.played?`${m.home_score}–${m.away_score}`:"Ej spelad"}</strong></div></article>)}</div>{matches.length===0&&<div className="admin-empty"><strong>Inga matcher tilldelade</strong><span>När cupadministratören tilldelar dig en match visas den här.</span></div>}</section></main>;
}
