"use client";
import {FormEvent,useCallback,useEffect,useState} from "react";
import {CLIENT_API_BASE} from "../lib/client-api";
import ReporterMatchEvents from "./reporter-match-events";
const API=CLIENT_API_BASE,KEY="cupnavi_reporter_session_v1";
type Cup={id:number;name:string;public_slug?:string|null};
type Match={id:number;stage?:string|null;home_team:string;away_team:string;home_score:number|null;away_score:number|null;home_penalties?:number|null;away_penalties?:number|null;status:string;scheduled_start?:string|null};
async function call<T>(path:string,token?:string|null,init:RequestInit={}):Promise<T>{const h=new Headers(init.headers);if(token)h.set("Authorization",`Bearer ${token}`);if(init.body)h.set("Content-Type","application/json");const r=await fetch(`${API}${path}`,{...init,headers:h,cache:"no-store"});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error(p?.detail||`API-fel ${r.status}`);return p as T;}
export default function ReporterClient(){
 const[cup,setCup]=useState(""),[code,setCode]=useState(""),[token,setToken]=useState<string|null>(null),[cupInfo,setCupInfo]=useState<Cup|null>(null),[matches,setMatches]=useState<Match[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const logout=useCallback(()=>{localStorage.removeItem(KEY);setToken(null);setCupInfo(null);setMatches([]);setMessage("");setError("")},[]);
 const load=useCallback(async(t:string)=>{const[s,r]=await Promise.all([call<{cup:Cup}>("/api/reporter/session",t),call<{matches:Match[]}>("/api/reporter/reporting",t)]);setCupInfo(s.cup);setMatches(r.matches||[])},[]);
 useEffect(()=>{const q=new URLSearchParams(window.location.search).get("cup");if(q)setCup(q);const stored=localStorage.getItem(KEY);if(stored){setToken(stored);void load(stored).catch(()=>logout())}},[load,logout]);
 async function login(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const r=await call<{token:string;cup:Cup}>("/api/reporter/session",null,{method:"POST",body:JSON.stringify({cup,code})});localStorage.setItem(KEY,r.token);setToken(r.token);setCupInfo(r.cup);setCode("");await load(r.token)}catch(err){setError(err instanceof Error?err.message:"Inloggningen misslyckades.")}finally{setBusy(false)}}
 async function save(m:Match,h:string,a:string,hp:string,ap:string){if(!token)return;setBusy(true);setError("");setMessage("");try{await call(`/api/reporter/reporting/matches/${m.id}`,token,{method:"PUT",body:JSON.stringify({home_score:Number(h),away_score:Number(a),home_penalties:hp===""?null:Number(hp),away_penalties:ap===""?null:Number(ap),expected_home_score:m.home_score,expected_away_score:m.away_score,expected_home_penalties:m.home_penalties??null,expected_away_penalties:m.away_penalties??null})});await load(token);setMessage("Resultatet är sparat. Matchhändelserna nedan är nu öppna för färdigspelade matcher.")}catch(err){setError(err instanceof Error?err.message:"Resultatet kunde inte sparas.")}finally{setBusy(false)}}
 if(!token)return <main className="reporter-page reporter-page--login"><header className="reporter-hero"><p className="kicker">CN//REPORTER</p><h1>Matchrapportör</h1><p>Logga in med cupens adress och den fyrsiffriga kod du fått av arrangören.</p></header><form className="admin-panel reporter-login" onSubmit={login}><div className="reporter-login__fields"><label><span>Cup</span><input value={cup} onChange={e=>setCup(e.target.value)} required placeholder="Cupens länk eller ID"/></label><label><span>4-siffrig kod</span><input inputMode="numeric" pattern="[0-9]{4}" maxLength={4} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,"").slice(0,4))} required placeholder="0000" autoComplete="one-time-code"/></label></div>{error&&<p className="reporter-alert reporter-alert--error" role="alert">{error}</p>}<div className="reporter-login__footer"><span>Koden skapas av cupadministratören.</span><button className="is-primary" disabled={busy||code.length!==4}>{busy?"Kontrollerar…":"Öppna matchrapportering"}</button></div></form></main>;
 return <main className="reporter-page"><header className="reporter-hero reporter-hero--session"><div><p className="kicker">CN//REPORTER</p><h1>{cupInfo?.name||"Matchrapportering"}</h1><p>Rapportera slutresultat först. Lägg sedan till målskyttar, assist och kort.</p></div><button type="button" onClick={logout}>Logga ut</button></header>{(error||message)&&<section className={`reporter-alert ${error?"reporter-alert--error":"reporter-alert--success"}`} role={error?"alert":"status"}><strong>{error?"Något gick fel":"Resultatet är sparat"}</strong><span>{error||message}</span></section>}<section className="admin-panel reporter-results"><div className="admin-panel__top"><span>1 / RESULTAT</span><strong>{matches.length} MATCHER</strong></div><div className="reporter-results__head"><div><h2>Rapportera resultat</h2><p>Fyll i båda lagens mål och spara matchen.</p></div><span className="admin-lock">REPORTER</span></div><div className="reporter-match-list">{matches.map(m=><ReporterMatch key={`${m.id}-${m.home_score}-${m.away_score}-${m.home_penalties}-${m.away_penalties}`} m={m} busy={busy} save={save}/>)}</div></section><ReporterMatchEvents token={token} onAuthError={logout}/></main>;
}
function ReporterMatch({m,busy,save}:{m:Match;busy:boolean;save:(m:Match,h:string,a:string,hp:string,ap:string)=>void}){const[h,setH]=useState(m.home_score==null?"":String(m.home_score)),[a,setA]=useState(m.away_score==null?"":String(m.away_score)),[hp,setHp]=useState(m.home_penalties==null?"":String(m.home_penalties)),[ap,setAp]=useState(m.away_penalties==null?"":String(m.away_penalties));useEffect(()=>{setH(m.home_score==null?"":String(m.home_score));setA(m.away_score==null?"":String(m.away_score));setHp(m.home_penalties==null?"":String(m.home_penalties));setAp(m.away_penalties==null?"":String(m.away_penalties))},[m]);const tied=m.stage!=="Gruppspel"&&h!==""&&a!==""&&Number(h)===Number(a);const saved=m.status==="played";return <article className={`reporter-match${saved?" is-saved":""}`}><div className="reporter-match__meta"><span>{m.scheduled_start?.replace("T"," ")||"Ej schemalagd"}</span><span>{m.stage||"Match"}</span>{saved&&<span className="reporter-match__saved">Sparad</span>}</div><div className="reporter-match__body"><div className="reporter-match__teams"><strong>{m.home_team}</strong><span>mot</span><strong>{m.away_team}</strong></div><div className="reporter-score" aria-label={`${m.home_team} mot ${m.away_team}`}><label><span>{m.home_team}</span><input aria-label={`Mål för ${m.home_team}`} type="number" min="0" value={h} onChange={e=>setH(e.target.value)}/></label><b>–</b><label><span>{m.away_team}</span><input aria-label={`Mål för ${m.away_team}`} type="number" min="0" value={a} onChange={e=>setA(e.target.value)}/></label>{tied&&<div className="reporter-penalties"><label>Straffar hemma<input aria-label="Hemmastraffar" type="number" min="0" value={hp} onChange={e=>setHp(e.target.value)} placeholder="0"/></label><label>Straffar borta<input aria-label="Bortastraffar" type="number" min="0" value={ap} onChange={e=>setAp(e.target.value)} placeholder="0"/></label></div>}<button type="button" disabled={busy||h===""||a===""||(tied&&(hp===""||ap===""))} onClick={()=>save(m,h,a,hp,ap)}>{saved?"Uppdatera":"Spara resultat"}</button></div></div></article>}
