"use client";
import {FormEvent,useCallback,useEffect,useState} from "react";
import {CLIENT_API_BASE} from "../lib/client-api";
const API=CLIENT_API_BASE,KEY="cupnavi_reporter_session_v1";
type Cup={id:number;name:string;public_slug?:string|null};
type Match={id:number;stage?:string|null;home_team:string;away_team:string;home_score:number|null;away_score:number|null;home_penalties?:number|null;away_penalties?:number|null;status:string;scheduled_start?:string|null};
async function call<T>(path:string,token?:string|null,init:RequestInit={}):Promise<T>{const h=new Headers(init.headers);if(token)h.set("Authorization",`Bearer ${token}`);if(init.body)h.set("Content-Type","application/json");const r=await fetch(`${API}${path}`,{...init,headers:h,cache:"no-store"});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error(p?.detail||`API-fel ${r.status}`);return p as T;}
export default function ReporterClient(){
 const[cup,setCup]=useState(""),[code,setCode]=useState(""),[token,setToken]=useState<string|null>(null),[cupInfo,setCupInfo]=useState<Cup|null>(null),[matches,setMatches]=useState<Match[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const load=useCallback(async(t:string)=>{const[s,r]=await Promise.all([call<{cup:Cup}>("/api/reporter/session",t),call<{matches:Match[]}>("/api/reporter/reporting",t)]);setCupInfo(s.cup);setMatches(r.matches||[])},[]);
 useEffect(()=>{const q=new URLSearchParams(window.location.search).get("cup");if(q)setCup(q);const stored=localStorage.getItem(KEY);if(stored){setToken(stored);void load(stored).catch(()=>{localStorage.removeItem(KEY);setToken(null)})}},[load]);
 async function login(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const r=await call<{token:string;cup:Cup}>("/api/reporter/session",null,{method:"POST",body:JSON.stringify({cup,code})});localStorage.setItem(KEY,r.token);setToken(r.token);setCupInfo(r.cup);setCode("");await load(r.token)}catch(err){setError(err instanceof Error?err.message:"Inloggningen misslyckades.")}finally{setBusy(false)}}
 function logout(){localStorage.removeItem(KEY);setToken(null);setCupInfo(null);setMatches([]);setMessage("");setError("")}
 async function save(m:Match,h:string,a:string,hp:string,ap:string){if(!token)return;setBusy(true);setError("");setMessage("");try{await call(`/api/reporter/reporting/matches/${m.id}`,token,{method:"PUT",body:JSON.stringify({home_score:Number(h),away_score:Number(a),home_penalties:hp===""?null:Number(hp),away_penalties:ap===""?null:Number(ap),expected_home_score:m.home_score,expected_away_score:m.away_score,expected_home_penalties:m.home_penalties??null,expected_away_penalties:m.away_penalties??null})});await load(token);setMessage("Resultatet är sparat.")}catch(err){setError(err instanceof Error?err.message:"Resultatet kunde inte sparas.")}finally{setBusy(false)}}
 if(!token)return <main className="admin-main" style={{maxWidth:680,margin:"24px auto"}}><header className="admin-pagehead"><div><p className="kicker">CN//REPORTER</p><h1>Matchrapportör</h1><p>Begränsad åtkomst för resultat och matchhändelser.</p></div></header><form className="admin-panel" onSubmit={login}><div className="admin-form-grid"><label>Cup<input value={cup} onChange={e=>setCup(e.target.value)} required placeholder="Cupens länk/ID"/></label><label>4-siffrig kod<input inputMode="numeric" pattern="[0-9]{4}" maxLength={4} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,"").slice(0,4))} required placeholder="0000"/></label></div>{error&&<p role="alert">{error}</p>}<div className="admin-form-footer"><span>Koden fås av cupadministratören.</span><button disabled={busy||code.length!==4}>{busy?"Kontrollerar…":"Logga in"}</button></div></form></main>;
 return <main className="admin-main" style={{maxWidth:920,margin:"24px auto"}}><header className="admin-pagehead"><div><p className="kicker">CN//REPORTER</p><h1>{cupInfo?.name||"Matchrapportering"}</h1><p>Endast resultat och matchhändelser. Cupinställningar är inte åtkomliga här.</p></div><button type="button" onClick={logout}>Logga ut</button></header>{(error||message)&&<section className="admin-panel"><strong>{error?"Fel":"Klart"}</strong><p>{error||message}</p></section>}<section className="admin-panel admin-teams"><div className="admin-panel__top"><span>MATCHER</span><strong>{matches.length} ST</strong></div><div className="admin-team-list">{matches.map(m=><ReporterMatch key={m.id} m={m} busy={busy} save={save}/>)}</div></section></main>;
}
function ReporterMatch({m,busy,save}:{m:Match;busy:boolean;save:(m:Match,h:string,a:string,hp:string,ap:string)=>void}){const[h,setH]=useState(m.home_score==null?"":String(m.home_score)),[a,setA]=useState(m.away_score==null?"":String(m.away_score)),[hp,setHp]=useState(m.home_penalties==null?"":String(m.home_penalties)),[ap,setAp]=useState(m.away_penalties==null?"":String(m.away_penalties));useEffect(()=>{setH(m.home_score==null?"":String(m.home_score));setA(m.away_score==null?"":String(m.away_score));setHp(m.home_penalties==null?"":String(m.home_penalties));setAp(m.away_penalties==null?"":String(m.away_penalties))},[m]);const tied=m.stage!=="Gruppspel"&&h!==""&&a!==""&&Number(h)===Number(a);return <article style={{display:"block"}}><div><strong>{m.home_team} – {m.away_team}</strong><small>{m.scheduled_start?.replace("T"," ")||"Ej schemalagd"} · {m.stage||"Match"}</small></div><div className="admin-team-actions" style={{marginTop:10,flexWrap:"wrap"}}><input aria-label="Hemmamål" type="number" min="0" value={h} onChange={e=>setH(e.target.value)} style={{width:70}}/><span>–</span><input aria-label="Bortamål" type="number" min="0" value={a} onChange={e=>setA(e.target.value)} style={{width:70}}/>{tied&&<><input aria-label="Hemmastraffar" type="number" min="0" value={hp} onChange={e=>setHp(e.target.value)} placeholder="Straff H" style={{width:90}}/><input aria-label="Bortastraffar" type="number" min="0" value={ap} onChange={e=>setAp(e.target.value)} placeholder="Straff B" style={{width:90}}/></>}<button type="button" disabled={busy||h===""||a===""||(tied&&(hp===""||ap===""))} onClick={()=>save(m,h,a,hp,ap)}>Spara</button></div></article>}
