"use client";
import {useCallback,useEffect,useState} from "react";
import {CLIENT_API_BASE} from "../lib/client-api";
const API=CLIENT_API_BASE;
type Status={active:boolean;created_at?:string|null;rotated_at?:string|null;expires_at?:string|null;valid_hours?:number;code?:string};
async function req<T>(path:string,token:string,init:RequestInit={}):Promise<T>{const h=new Headers(init.headers);h.set("Authorization",`Bearer ${token}`);if(init.body)h.set("Content-Type","application/json");const r=await fetch(`${API}${path}`,{...init,headers:h,cache:"no-store"});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error(p?.detail||`API-fel ${r.status}`);return p as T;}
export default function RoleCodeAdmin({token,cupId}:{token:string;cupId:number;publicSlug?:string|null}){
 const[data,setData]=useState<Status|null>(null),[newCode,setNewCode]=useState(""),[validHours,setValidHours]=useState(48),[busy,setBusy]=useState(false),[error,setError]=useState(""),[copied,setCopied]=useState(false);
 const load=useCallback(async()=>{setBusy(true);try{const status=await req<Status>(`/api/admin/cups/${cupId}/role-codes/reporter`,token);setData(status);setValidHours(status.valid_hours||48);setError("")}catch(e){setError(e instanceof Error?e.message:"Koden kunde inte hämtas.")}finally{setBusy(false)}},[cupId,token]);
 useEffect(()=>{setNewCode("");void load()},[load]);
 async function rotate(){if(data?.active&&!window.confirm("Skapa en ny matchrapportörskod? Den gamla koden och alla aktiva rapportörssessioner slutar fungera direkt."))return;setBusy(true);setError("");try{const r=await req<Status>(`/api/admin/cups/${cupId}/role-codes/reporter/rotate`,token,{method:"POST",body:JSON.stringify({valid_hours:validHours})});setData(r);setNewCode(r.code||"")}catch(e){setError(e instanceof Error?e.message:"Koden kunde inte skapas.")}finally{setBusy(false)}}
 const reporterLink="/reporter";
 async function copyLink(){try{await navigator.clipboard.writeText(new URL(reporterLink,window.location.origin).toString());setCopied(true);window.setTimeout(()=>setCopied(false),2000)}catch{setError("Länken kunde inte kopieras. Öppna rapportörsvyn och kopiera adressen manuellt.")}}
 const deadline=data?.expires_at?new Date(data.expires_at).toLocaleString("sv-SE",{dateStyle:"short",timeStyle:"short"}):null;
 return <section className="admin-panel" id="role-codes"><div className="admin-panel__top"><span>BEHÖRIGHET / MATCHRAPPORTÖR</span><strong>{data?.active?"KOD AKTIV":data?.expires_at?"KOD UTGÅNGEN":"INGEN KOD"}</strong></div><div className="admin-cupinfo__head"><div><h2>Matchrapportör</h2><p>Ge en funktionär en separat 4-siffrig kod. Den ger bara åtkomst till resultat och matchhändelser – inte cupinställningar.</p></div><span className="admin-lock">BEGRÄNSAD ROLL</span></div>{error&&<div className="admin-code-placeholder"><b>Fel</b> · {error}</div>}{newCode&&<div className="admin-code-placeholder" style={{marginTop:14,textAlign:"center"}}><small>NY KOD · VISAS NU</small><div style={{fontSize:"2rem",fontWeight:900,letterSpacing:".22em"}}>{newCode}</div><small>Kopiera koden nu. Den går inte att läsa tillbaka senare.</small></div>}<label style={{display:"grid",gap:6,marginTop:14,maxWidth:280}}><strong>Kodens giltighet från skapandet</strong><select value={validHours} disabled={busy} onChange={e=>setValidHours(Number(e.target.value))}><option value={8}>8 timmar</option><option value={12}>12 timmar</option><option value={24}>1 dygn</option><option value={48}>2 dygn</option><option value={72}>3 dygn</option></select><small>Högst 3 dygn. En inloggning förlänger inte tiden.</small></label><div className="admin-form-footer"><span>{deadline?`${data?.active?"Gäller till":"Gick ut"} ${deadline}`:"Ingen matchrapportörskod skapad ännu."}</span><div className="admin-team-actions"><button type="button" onClick={()=>void copyLink()}>{copied?"Länk kopierad ✓":"Kopiera inloggningslänk"}</button><a href={reporterLink} target="_blank" rel="noreferrer">Testa rapportörsvy ↗</a><button type="button" disabled={busy} onClick={()=>void rotate()}>{busy?"Arbetar…":data?.active?"Regenerera kod":"Generera 4-siffrig kod"}</button></div></div></section>;
}
