"use client";
import {useCallback,useEffect,useState} from "react";
import {CLIENT_API_BASE} from "../lib/client-api";
const API=CLIENT_API_BASE;
type Status={active:boolean;created_at?:string|null;rotated_at?:string|null;expires_at?:string|null;valid_hours?:number;code?:string|null};
async function req<T>(path:string,token:string,init:RequestInit={}):Promise<T>{const h=new Headers(init.headers);h.set("Authorization",`Bearer ${token}`);if(init.body)h.set("Content-Type","application/json");const r=await fetch(`${API}${path}`,{...init,headers:h,cache:"no-store"});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error(p?.detail||`API-fel ${r.status}`);return p as T;}
export default function RoleCodeAdmin({token,cupId,publicSlug}:{token:string;cupId:number;publicSlug?:string|null}){
 const[data,setData]=useState<Status|null>(null),[newCode,setNewCode]=useState(""),[validHours,setValidHours]=useState(48),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[copied,setCopied]=useState<"code"|"link"|null>(null);
 const load=useCallback(async()=>{setLoading(true);try{const status=await req<Status>(`/api/admin/cups/${cupId}/role-codes/reporter`,token);setData(status);setNewCode(status.code||"");setValidHours(status.valid_hours||48);setError("")}catch(e){setError(e instanceof Error?e.message:"Koden kunde inte hämtas.")}finally{setLoading(false)}},[cupId,token]);
 useEffect(()=>{setNewCode("");void load()},[load]);
 async function rotate(){if(data?.active&&!window.confirm("Skapa en ny matchrapportörskod? Den gamla koden och alla aktiva rapportörssessioner slutar fungera direkt."))return;setBusy(true);setError("");try{const r=await req<Status>(`/api/admin/cups/${cupId}/role-codes/reporter/rotate`,token,{method:"POST",body:JSON.stringify({valid_hours:validHours})});setData(r);setNewCode(r.code||"")}catch(e){setError(e instanceof Error?e.message:"Koden kunde inte skapas.")}finally{setBusy(false)}}
 async function copyCode(){try{if(!data?.active||!newCode)return;await navigator.clipboard.writeText(newCode);setCopied("code");window.setTimeout(()=>setCopied(null),2000)}catch{setError("Koden kunde inte kopieras. Markera och kopiera den manuellt.")}}
 const reporterLink=`/reporter?cup=${encodeURIComponent(publicSlug||String(cupId))}`;
 async function copyLink(){try{await navigator.clipboard.writeText(new URL(reporterLink,window.location.origin).toString());setCopied("link");window.setTimeout(()=>setCopied(null),2000)}catch{setError("Länken kunde inte kopieras. Öppna rapportörsvyn och kopiera adressen manuellt.")}}
 const [now,setNow]=useState(Date.now());
 useEffect(()=>{const timer=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(timer)},[]);
 const remaining=data?.expires_at?Math.max(0,new Date(data.expires_at).getTime()-now):0;
 const remainingLabel=remaining?`${Math.floor(remaining/86400000)} dygn ${Math.floor(remaining%86400000/3600000)} h ${Math.floor(remaining%3600000/60000)} min`:"Utgången";
 const deadline=data?.expires_at?new Date(data.expires_at).toLocaleString("sv-SE",{dateStyle:"short",timeStyle:"short"}):null;
 async function extend(){setBusy(true);setError("");try{const status=await req<Status>(`/api/admin/cups/${cupId}/role-codes/reporter/extend`,token,{method:"POST",body:JSON.stringify({additional_hours:24})});setData(status);setNewCode(status.code||"")}catch(e){setError(e instanceof Error?e.message:"Koden kunde inte förlängas.")}finally{setBusy(false)}}
 async function remove(){if(!window.confirm("Ta bort rapportörskoden? Alla aktiva rapportörssessioner slutar fungera."))return;setBusy(true);setError("");try{setData(await req<Status>(`/api/admin/cups/${cupId}/role-codes/reporter`,token,{method:"DELETE"}));setNewCode("")}catch(e){setError(e instanceof Error?e.message:"Koden kunde inte tas bort.")}finally{setBusy(false)}}
 return <section className="admin-panel" id="role-codes"><div className="admin-panel__top"><span>BEHÖRIGHET / MATCHRAPPORTÖR</span><strong>{loading?"HÄMTAR":data?.active?"KOD AKTIV":data?.expires_at?"KOD UTGÅNGEN":"INGEN KOD"}</strong></div><div className="admin-cupinfo__head"><div><h2>Matchrapportör</h2><p>Ge en funktionär en separat 4-siffrig kod. Den ger bara åtkomst till resultat och matchhändelser – inte cupinställningar.</p></div><span className="admin-lock">BEGRÄNSAD ROLL</span></div>{error&&<div className="admin-code-placeholder" role="alert"><b>Fel</b> · {error}{!data&&<button type="button" onClick={()=>void load()}>Försök igen</button>}</div>}{data?.active&&newCode&&<div className="admin-code-placeholder reporter-admin-code" style={{marginTop:14,textAlign:"center"}}><small>AKTIV RAPPORTÖRSKOD</small><div style={{fontSize:"2rem",fontWeight:900,letterSpacing:".22em"}}>{newCode}</div><small>Samma kod gäller när du återvänder. Att kopiera koden påverkar inga inloggningar.</small></div>}{data?.active&&<div className="admin-code-placeholder"><span>Återstår</span><b>{remainingLabel}</b></div>}{data?.active&&!newCode&&<p className="admin-code-placeholder">Den äldre koden kan inte visas igen. Den fortsätter fungera. Byt kod endast om du behöver en ny; aktiva rapportörer måste då logga in igen.</p>}<label style={{display:"grid",gap:6,marginTop:14,maxWidth:280}}><strong>Kodens giltighet från skapandet</strong><select value={validHours} disabled={busy||loading} onChange={e=>setValidHours(Number(e.target.value))}><option value={8}>8 timmar</option><option value={12}>12 timmar</option><option value={24}>1 dygn</option><option value={48}>2 dygn</option><option value={72}>3 dygn</option></select><small>Högst 3 dygn. En inloggning förlänger inte tiden.</small></label><div className="admin-form-footer"><span aria-live="polite">{loading?"Hämtar kodstatus…":deadline?`${data?.active?"Gäller till":"Gick ut"} ${deadline}`:data?"Ingen matchrapportörskod skapad ännu.":"Kodstatus kunde inte hämtas."}</span><div className="admin-team-actions">{data?.active&&newCode&&<button className="role-code-primary" type="button" disabled={busy} onClick={()=>void copyCode()}>{copied==="code"?"Kopierat ✓":"Kopiera kod"}</button>}<button className={data?.active?"admin-action-secondary":"role-code-primary"} type="button" disabled={busy||loading||!data} onClick={()=>void rotate()}>{busy?"Arbetar…":loading?"Hämtar kodstatus…":data?.active?"Byt kod":"Generera 4-siffrig kod"}</button><button type="button" onClick={()=>void copyLink()}>{copied==="link"?"Kopierat ✓":"Kopiera inloggningslänk"}</button><a href={reporterLink} target="_blank" rel="noreferrer">Testa rapportörsvy ↗</a>{data?.active&&<><button type="button" disabled={busy} onClick={()=>void extend()}>Förläng 24 timmar</button><button type="button" disabled={busy} onClick={()=>void remove()}>Ta bort kod</button></>}</div></div></section>;
}
