"use client";
import {FormEvent,useCallback,useEffect,useState} from "react";
import {CLIENT_API_BASE} from "../lib/client-api";
const API=CLIENT_API_BASE;
type Player={id:number;team_id:number;name:string;player_number?:number|null};
type Team={id:number;name:string;age_class?:string|null;players:Player[]};
type Payload={teams:Team[]};
async function api<T>(path:string,token:string,init:RequestInit={}):Promise<T>{const h=new Headers(init.headers);h.set("Authorization",`Bearer ${token}`);if(init.body)h.set("Content-Type","application/json");const r=await fetch(`${API}${path}`,{...init,headers:h,cache:"no-store"});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error(p?.detail||`API-fel ${r.status}`);return p as T;}
export default function RosterAdmin({token,cupId}:{token:string;cupId:number}){
 const[data,setData]=useState<Payload|null>(null),[teamId,setTeamId]=useState<number|null>(null),[name,setName]=useState(""),[number,setNumber]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const load=useCallback(async()=>{setBusy(true);try{const p=await api<Payload>(`/api/admin/cups/${cupId}/players`,token);setData(p);setTeamId(current=>current&&p.teams.some(t=>t.id===current)?current:(p.teams[0]?.id??null));setError("")}catch(e){setError(e instanceof Error?e.message:"Trupperna kunde inte hämtas.")}finally{setBusy(false)}},[cupId,token]);
 useEffect(()=>{void load()},[load]);
 async function add(e:FormEvent){e.preventDefault();if(!teamId||!name.trim())return;setBusy(true);setError("");setMessage("");try{await api(`/api/admin/cups/${cupId}/teams/${teamId}/players`,token,{method:"POST",body:JSON.stringify({name:name.trim(),player_number:number===""?null:Number(number)})});setName("");setNumber("");setMessage("Spelaren har lagts till.");await load()}catch(err){setError(err instanceof Error?err.message:"Spelaren kunde inte läggas till.")}finally{setBusy(false)}}
 async function remove(player:Player){if(!window.confirm(`Ta bort ${player.name} ur truppen?`))return;setBusy(true);setError("");setMessage("");try{await api(`/api/admin/cups/${cupId}/teams/${player.team_id}/players/${player.id}`,token,{method:"DELETE"});setMessage(`${player.name} har tagits bort.`);await load()}catch(err){setError(err instanceof Error?err.message:"Spelaren kunde inte tas bort.")}finally{setBusy(false)}}
 async function quickEdit(player:Player){const newName=window.prompt("Spelarnamn",player.name);if(newName===null)return;const newNumber=window.prompt("Tröjnummer (tomt = inget)",player.player_number==null?"":String(player.player_number));if(newNumber===null)return;setBusy(true);setError("");setMessage("");try{await api(`/api/admin/cups/${cupId}/teams/${player.team_id}/players/${player.id}`,token,{method:"PUT",body:JSON.stringify({name:newName,player_number:newNumber.trim()===""?null:Number(newNumber)})});setMessage("Spelaren har uppdaterats.");await load()}catch(err){setError(err instanceof Error?err.message:"Spelaren kunde inte uppdateras.")}finally{setBusy(false)}}
 if(!data)return <section className="admin-panel" id="players"><div className="admin-panel__top"><span>TRUPPER</span><strong>{busy?"HÄMTAR":"SAKNAS"}</strong></div><h2>Spelare</h2><p>{error||"Hämtar trupper…"}</p></section>;
 const selected=data.teams.find(t=>t.id===teamId)||null;
 return <section className="admin-panel admin-teams" id="players"><div className="admin-panel__top"><span>TRUPPER / SPELARE</span><strong>{data.teams.reduce((n,t)=>n+t.players.length,0)} SPELARE</strong></div><div className="admin-cupinfo__head"><div><h2>Trupper</h2><p>Spelarna används direkt av målskyttar, assist och kort i matchrapporteringen.</p></div><span className="admin-lock">LIVE DATA</span></div>{(error||message)&&<div className="admin-code-placeholder" style={{marginBottom:16}}><b>{error?"Fel":"Klart"}</b> · {error||message}</div>}<div className="admin-form-grid"><label>Lag<select value={teamId??""} onChange={e=>setTeamId(Number(e.target.value))}>{data.teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label></div>{selected&&<><form className="admin-team-editor" onSubmit={add}><div className="admin-form-grid"><label>Spelarnamn<input value={name} onChange={e=>setName(e.target.value)} placeholder="Exempel: Alex Andersson" required/></label><label>Tröjnummer<input type="number" min="0" max="999" value={number} onChange={e=>setNumber(e.target.value)} placeholder="10"/></label></div><div className="admin-form-footer"><span>{selected.players.length} spelare i {selected.name}</span><button type="submit" disabled={busy||!name.trim()}>{busy?"Sparar…":"Lägg till spelare"}</button></div></form><div className="admin-team-list">{selected.players.length?selected.players.map(player=><article key={player.id}><div><strong>{player.player_number==null?"–":`#${player.player_number}`} · {player.name}</strong><small>{selected.name}</small></div><div className="admin-team-actions"><button type="button" disabled={busy} onClick={()=>void quickEdit(player)}>Redigera</button><button type="button" className="is-danger" disabled={busy} onClick={()=>void remove(player)}>Ta bort</button></div></article>):<div className="admin-empty"><strong>Ingen trupp registrerad</strong><span>Lägg till spelarna ovan. Matchhändelser kan registreras först när spelare finns.</span></div>}</div></>}</section>;
}
