"use client";
import {FormEvent,useCallback,useEffect,useState} from "react";
import {CLIENT_API_BASE} from "../lib/client-api";
const API=CLIENT_API_BASE,KEY="cupnavi_team_session_v1";
type Cup={id:number;name:string;public_slug?:string|null;start_date?:string|null;end_date?:string|null;arena_address?:string|null;public_information?:string|null};
type Team={id:number;name:string;age_class?:string|null;group_id?:number|null};
type Player={id:number;name:string;player_number?:number|null};
type Match={id:number;stage?:string|null;match_no?:number|null;scheduled_start?:string|null;pitch_number?:number|null;home_team:string;away_team:string;home_score?:number|null;away_score?:number|null;played:boolean};
type Portal={cup:Cup;team:Team;players:Player[];matches:Match[]};
async function call<T>(path:string,token?:string|null,init:RequestInit={}):Promise<T>{const h=new Headers(init.headers);if(token)h.set("Authorization",`Bearer ${token}`);if(init.body)h.set("Content-Type","application/json");const r=await fetch(`${API}${path}`,{...init,headers:h,cache:"no-store"});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error(p?.detail||`API-fel ${r.status}`);return p as T;}
export default function TeamClient(){
 const[cup,setCup]=useState(""),[teamId,setTeamId]=useState(""),[code,setCode]=useState(""),[token,setToken]=useState<string|null>(null),[data,setData]=useState<Portal|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const logout=useCallback(()=>{localStorage.removeItem(KEY);setToken(null);setData(null);setError("")},[]);
 const load=useCallback(async(t:string)=>{setData(await call<Portal>("/api/team/portal",t))},[]);
 useEffect(()=>{const q=new URLSearchParams(window.location.search);const c=q.get("cup"),team=q.get("team");if(c)setCup(c);if(team)setTeamId(team);const stored=localStorage.getItem(KEY);if(stored){setToken(stored);void load(stored).catch(()=>logout())}},[load,logout]);
 async function login(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const r=await call<{token:string}>("/api/team/session",null,{method:"POST",body:JSON.stringify({cup,team_id:Number(teamId),code})});localStorage.setItem(KEY,r.token);setToken(r.token);setCode("");await load(r.token)}catch(err){setError(err instanceof Error?err.message:"Inloggningen misslyckades.")}finally{setBusy(false)}}
 if(!token||!data)return <main className="admin-main" style={{maxWidth:680,margin:"24px auto"}}><header className="admin-pagehead"><div><p className="kicker">CN//TEAM</p><h1>Lagportal</h1><p>En enkel vy för lagledaren – bara det egna laget och det som behövs under cupen.</p></div></header><form className="admin-panel" onSubmit={login}><div className="admin-form-grid"><label>Cup<input value={cup} onChange={e=>setCup(e.target.value)} required placeholder="Cupens länk/ID"/></label><label>Lag-ID<input inputMode="numeric" value={teamId} onChange={e=>setTeamId(e.target.value.replace(/\D/g,""))} required placeholder="ID"/></label><label>4-siffrig kod<input inputMode="numeric" pattern="[0-9]{4}" maxLength={4} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,"").slice(0,4))} required placeholder="0000"/></label></div>{error&&<p role="alert">{error}</p>}<div className="admin-form-footer"><span>Använd länken och lagkoden från cupadministratören.</span><button disabled={busy||code.length!==4||!teamId}>{busy?"Kontrollerar…":"Logga in"}</button></div></form></main>;
 return <main className="admin-main" style={{maxWidth:920,margin:"24px auto"}}><header className="admin-pagehead"><div><p className="kicker">CN//TEAM</p><h1>{data.team.name}</h1><p>{data.cup.name}{data.team.age_class?` · ${data.team.age_class}`:""}</p></div><button type="button" onClick={logout}>Logga ut</button></header>{error&&<section className="admin-panel"><strong>Fel</strong><p>{error}</p></section>}<section className="admin-panel"><div className="admin-panel__top"><span>CUPINFO</span><strong>LAGVY</strong></div><div className="admin-cupinfo__head"><div><h2>{data.cup.name}</h2><p>{[data.cup.start_date&&data.cup.end_date?`${data.cup.start_date}–${data.cup.end_date}`:data.cup.start_date,data.cup.arena_address].filter(Boolean).join(" · ")||"Cupinformation"}</p></div><span className="admin-lock">EGET LAG</span></div>{data.cup.public_information&&<p>{data.cup.public_information}</p>}</section><section className="admin-panel admin-teams"><div className="admin-panel__top"><span>MINA MATCHER</span><strong>{data.matches.length}</strong></div><div className="admin-team-list">{data.matches.map(m=><article key={m.id}><div><strong>{m.home_team} – {m.away_team}</strong><small>{m.scheduled_start?.replace("T"," ")||"Ej schemalagd"}{m.pitch_number?` · plan ${m.pitch_number}`:""}{m.stage?` · ${m.stage}`:""}{m.match_no?` · match ${m.match_no}`:""}</small></div><strong>{m.played?`${m.home_score}–${m.away_score}`:"Ej spelad"}</strong></article>)}</div>{data.matches.length===0&&<div className="admin-empty"><strong>Inga publicerade matcher ännu</strong><span>När schemat är publicerat visas lagets matcher här.</span></div>}</section><section className="admin-panel admin-teams"><div className="admin-panel__top"><span>TRUPP</span><strong>{data.players.length} SPELARE</strong></div><div className="admin-team-list">{data.players.map(p=><article key={p.id}><div><strong>{p.player_number!=null?`${p.player_number} · `:""}{p.name}</strong></div></article>)}</div>{data.players.length===0&&<div className="admin-empty"><strong>Ingen spelarlista registrerad</strong><span>Kontakta cupadministratören om truppen ska läggas in.</span></div>}</section></main>;
}
