"use client";
import {useCallback,useEffect,useState} from "react";
import {CLIENT_API_BASE} from "../lib/client-api";
const API=CLIENT_API_BASE;
type Team={id:number;name:string;age_class?:string|null;code_active:boolean;rotated_at?:string|null};
type Payload={teams:Team[]};
async function req<T>(path:string,token:string,init:RequestInit={}):Promise<T>{const h=new Headers(init.headers);h.set("Authorization",`Bearer ${token}`);if(init.body)h.set("Content-Type","application/json");const r=await fetch(`${API}${path}`,{...init,headers:h,cache:"no-store"});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error(p?.detail||`API-fel ${r.status}`);return p as T;}
export default function TeamRoleCodeAdmin({token,cupId,publicSlug}:{token:string;cupId:number;publicSlug?:string|null}){
 const[data,setData]=useState<Payload|null>(null),[codes,setCodes]=useState<Record<number,string>>({}),[busy,setBusy]=useState<number|null>(null),[error,setError]=useState("");
 const load=useCallback(async()=>{try{setData(await req<Payload>(`/api/admin/cups/${cupId}/role-codes/teams`,token));setError("")}catch(e){setError(e instanceof Error?e.message:"Lagkoderna kunde inte hämtas.")}},[cupId,token]);
 useEffect(()=>{setCodes({});void load()},[load]);
 async function rotate(team:Team){if(team.code_active&&!window.confirm(`Skapa ny lagkod för ${team.name}? Den gamla koden och aktiva lagsessioner slutar fungera direkt.`))return;setBusy(team.id);setError("");try{const r=await req<{code:string}>(`/api/admin/cups/${cupId}/role-codes/teams/${team.id}/rotate`,token,{method:"POST"});setCodes(current=>({...current,[team.id]:r.code}));await load()}catch(e){setError(e instanceof Error?e.message:"Lagkoden kunde inte skapas.")}finally{setBusy(null)}}
 const base=publicSlug?encodeURIComponent(publicSlug):String(cupId);
 return <section className="admin-panel" id="team-codes"><div className="admin-panel__top"><span>BEHÖRIGHET / LAG</span><strong>{data?.teams.filter(t=>t.code_active).length||0} KODER</strong></div><div className="admin-cupinfo__head"><div><h2>Lagportal</h2><p>Varje lag får en egen 4-siffrig kod. Lagledaren ser bara det egna laget, spelarlistan och lagets matcher.</p></div><span className="admin-lock">LAGISOLERAD</span></div>{error&&<div className="admin-code-placeholder"><b>Fel</b> · {error}</div>}<div className="admin-team-list">{data?.teams.map(t=><article key={t.id}><div><strong>{t.name}</strong><small>{t.age_class?`${t.age_class} · `:""}{t.code_active?`Kod aktiv${t.rotated_at?` · ändrad ${String(t.rotated_at).replace("T"," ")}`:""}`:"Ingen kod skapad"}</small>{codes[t.id]&&<div className="admin-code-placeholder" style={{marginTop:8,textAlign:"center"}}><small>NY KOD · VISAS NU</small><div style={{fontSize:"1.7rem",fontWeight:900,letterSpacing:".22em"}}>{codes[t.id]}</div></div>}</div><div className="admin-team-actions"><a href={`/team?cup=${base}&team=${t.id}`} target="_blank" rel="noreferrer">Öppna lagvy ↗</a><button type="button" disabled={busy!==null} onClick={()=>void rotate(t)}>{busy===t.id?"Arbetar…":t.code_active?"Regenerera kod":"Generera kod"}</button></div></article>)}</div>{data&&data.teams.length===0&&<div className="admin-empty"><strong>Inga lag ännu</strong><span>Lägg först till lag i cupen.</span></div>}</section>;
}
